require('./master-offline-guard.cjs');
require('reflect-metadata');
const {test}=require('node:test'),assert=require('node:assert/strict');
const {AdminService}=require('../dist/modules/admin/admin.service');
const actor={userId:'admin01-unit-admin',selectedFactoryId:'unit-factory',role:'ADMIN',isAdmin:true,isGuest:false,permissions:[]};
function setup(){const trace=[],factory={id:'unit-factory',name:'Участок',code:'unit-factory',isActive:true,deletedAt:null},line={id:'unit-line',factoryId:factory.id,name:'Линия',status:'STOP',deletedAt:null,positions:[],staffingTemplates:[]},position={id:'unit-position',factoryId:factory.id,lineId:line.id,name:'Позиция',isActive:true,deletedAt:null,line};
 const tx={factory:{findUnique:async()=>factory,findFirst:async args=>args.where.id===factory.id?factory:null,update:async args=>Object.assign(factory,args.data)},line:{findFirst:async args=>args.where.id===line.id?line:null,create:async args=>Object.assign(line,args.data),update:async args=>Object.assign(line,args.data)},linePosition:{findFirst:async()=>position,create:async args=>Object.assign(position,args.data),update:async args=>Object.assign(position,args.data)},assignment:{count:async()=>0}};
 const service=new AdminService({db:{$transaction:async fn=>{const result=await fn(tx);trace.push('commit');return result;}}},{writeTx:async(_tx,event)=>trace.push({audit:event})},{broadcast:(type,payload)=>trace.push({type,payload})},{},{});return{service,tx,trace,line,position,factory};}
for(const kind of ['createLine','updateLine','createPosition','updatePosition'])test(`Admin ${kind}: same existing scoped invalidation only after commit`,async()=>{const h=setup(),args=kind==='createLine'?[{name:'Линия новая'}]:kind==='updateLine'?['unit-line',{name:'Линия новая'}]:kind==='createPosition'?['unit-line',{name:'Позиция новая'}]:['unit-line','unit-position',{name:'Позиция новая'}];await h.service[kind](actor,...args);const event=h.trace.at(-1);assert.equal(event.type,'line_updated');assert.deepEqual(event.payload,{factoryId:'unit-factory',lineId:'unit-line',type:'CONFIGURATION_UPDATED'});assert.equal(h.trace.at(-2),'commit');assert.equal(h.trace.filter(x=>x.type).length,1);});
test('factory edit is same-factory ADMIN only; name/code/audit, no access mutation',async()=>{const h=setup();await assert.rejects(h.service.updateFactory({...actor,role:'MASTER',isAdmin:false},'unit-factory',{name:'Нельзя'}));await assert.rejects(h.service.updateFactory(actor,'foreign',{name:'Нельзя'}));assert.equal(h.trace.length,0);const r=await h.service.updateFactory(actor,'unit-factory',{name:'Новое имя',code:'new-code',reason:'Проверка'});assert.equal(r.name,'Новое имя');assert.equal(r.code,'new-code');assert.equal(h.trace[0].audit.action,'FACTORY_UPDATED');assert.deepEqual(Object.keys(h.trace[0].audit.details.newValue).sort(),['code','name']);});
test('factory empty/invalid/duplicate code rejects without commit or audit',async()=>{for(const body of [{name:''},{name:12},{code:''}]){const h=setup();await assert.rejects(h.service.updateFactory(actor,'unit-factory',body));assert.equal(h.trace.length,0);}const h=setup();h.tx.factory.findFirst=async args=>args.where.id==='unit-factory'?h.factory:{id:'other'};await assert.rejects(h.service.updateFactory(actor,'unit-factory',{code:'other'}));assert.equal(h.trace.length,0);});
test('failed line transaction cannot emit success invalidation',async()=>{const h=setup();h.tx.line.update=async()=>{throw Error('controlled rollback');};await assert.rejects(h.service.updateLine(actor,'unit-line',{name:'Изменение'}));assert.equal(h.trace.filter(x=>x.type).length,0);});
