require('./master-offline-guard.cjs');require('reflect-metadata');
const {test}=require('node:test'),assert=require('node:assert/strict');
const {memory}=require('./master-r2-memory.cjs');
const {operationLockKey}=require('../dist/common/operation-lock');
const {assertAttendanceAccessTx,assertNoForeignAttendanceTx,isSentHomeAwaitingReturn}=require('../dist/common/shift-attendance');
const {EmployeeService}=require('../dist/modules/employee/employee.service');
const {ShiftService}=require('../dist/modules/shift/shift.service');
const {factoryShiftTarget,factoryShiftWindow}=require('../dist/common/shift-time');
const master={userId:'master',selectedFactoryId:'C',role:'MASTER',isAdmin:false,isGuest:false,permissions:['assignments.manage','shift.return.manage']};
function setup(){const m=memory(),person={id:'worker',factoryId:'A0',employeeState:'AVAILABLE',version:0,blockedAt:null,deletedAt:null},access={userId:'worker',factoryId:'C',isActive:true,isGuest:false,role:'WORKER'},sessions=[{id:'s',factoryId:'C',userId:'worker',status:'ACTIVE'}],assignments=[],requests=[],audits=m.audits,settings={factoryId:'C',sendHomeRequiresComment:true,returnRequestEnabled:true};
 m.data.user=m.model('user',[person]);m.data.userFactoryAccess=m.model('access',[access],{compounds:['userId_factoryId']});m.data.shiftSession=m.model('session',sessions);m.data.assignment=m.model('assignment',assignments);m.data.shiftSettings=m.model('settings',[settings]);m.data.shiftReturnRequest=m.model('return',requests,{defaults:{status:'PENDING'}});m.data.auditLog=m.model('audit',audits);
 const e=new EmployeeService({db:m.db},m.ws,m.audit),s=new ShiftService({db:m.db},e,m.audit,{notifyShiftReturnRequested:async()=>{}},{},m.ws);return{...m,e,s,person,access,sessions,assignments,requests,audits,settings};}
test('actual person lock is shared across UFA; plans keep factory scope',()=>{assert.equal(operationLockKey.assignmentUser('A0','person'),operationLockKey.assignmentUser('C','person'));assert.notEqual(operationLockKey.plannedUser('A0',new Date(0),'DAY','person'),operationLockKey.plannedUser('C',new Date(0),'DAY','person'));});
for(const flag of['valid-secondary','revoked','guest','blocked','deleted','foreign-session','foreign-assignment'])test(`attendance guard ${flag}`,async()=>{const f=setup();if(flag==='revoked')f.access.isActive=false;if(flag==='guest')f.access.isGuest=true;if(flag==='blocked')f.person.blockedAt=new Date();if(flag==='deleted')f.person.deletedAt=new Date();if(flag==='foreign-session')f.sessions.push({id:'foreign',factoryId:'A0',userId:'worker',status:'ACTIVE'});if(flag==='foreign-assignment')f.assignments.push({id:'foreign',factoryId:'A0',userId:'worker',endedAt:null});if(flag==='valid-secondary')assert.equal((await assertAttendanceAccessTx(f.db,'C','worker')).user.factoryId,'A0');else await assert.rejects(assertAttendanceAccessTx(f.db,'C','worker'),e=>e.getStatus()===409);assert.equal(f.writes.length,0);});
for(const required of[true,false])test(`send home existing setting ${required} controls optional comment`,async()=>{const f=setup();f.settings.sendHomeRequiresComment=required;if(required)await assert.rejects(f.e.sendHome('worker',master,''),/комментарий/);else{await f.e.sendHome('worker',master,'');assert.equal(f.person.employeeState,'OFF_SHIFT');assert.equal(f.audits.find(v=>v.action==='EMPLOYEE_SENT_HOME').factoryId,'C');assert.equal(f.audits.find(v=>v.action==='EMPLOYEE_SENT_HOME').details.comment,null);await assert.rejects(f.e.sendHome('worker',master,''),/уже отправлен/);assert.equal(f.audits.filter(v=>v.action==='EMPLOYEE_SENT_HOME').length,1);}});
test('no factual C presence cannot send home even with global AVAILABLE',async()=>{const f=setup();f.sessions.length=0;await assert.rejects(f.e.sendHome('worker',master,'Комментарий'),/не присутствует/);assert.equal(f.writes.length,0);});
test('return request needs scoped canonical provenance, not global OFF_SHIFT',async()=>{const f=setup();f.person.employeeState='OFF_SHIFT';await assert.rejects(f.s.createReturnRequest({...master,userId:'worker'},{reason:'Вернуться'}),/этого завода/);const now=new Date();f.audits.push({factoryId:'C',action:'EMPLOYEE_SENT_HOME',entityType:'User',entityId:'worker',createdAt:now});assert.equal(await isSentHomeAwaitingReturn(f.db,'A0','worker'),false);assert.equal(await isSentHomeAwaitingReturn(f.db,'C','worker'),true);await f.s.createReturnRequest({...master,userId:'worker'},{reason:'Вернуться'});await assert.rejects(f.s.createReturnRequest({...master,userId:'worker'},{reason:'Дубль'}),/ожидает/);});
test('approval dated before last send-home or stale request does not clear provenance',async()=>{const f=setup(),now=new Date(),target=factoryShiftTarget();f.audits.push({factoryId:'C',action:'EMPLOYEE_SENT_HOME',entityType:'User',entityId:'worker',createdAt:now});f.requests.push({factoryId:'C',userId:'worker',status:'APPROVED',decidedAt:new Date(now.getTime()-1)});assert.equal(await isSentHomeAwaitingReturn(f.db,'C','worker'),true);assert.equal(await isSentHomeAwaitingReturn(f.db,'C','worker',target,new Date(now.getTime()-1)),false);});
test('invalid decision and rejection without reason are denied before writes',async()=>{const f=setup();await assert.rejects(f.s.decideReturnRequest(master,'id',{status:'OTHER'}),/решение/);await assert.rejects(f.s.decideReturnRequest(master,'id',{status:'REJECTED'}),/причину/);assert.equal(f.writes.length,0);});
