// Isolated production-service regression. No SQL/live/storage claim.
require('./master-offline-guard.cjs');require('reflect-metadata');
const {test}=require('node:test'),assert=require('node:assert/strict'),{memory,denied}=require('./master-r2-memory.cjs');
const {AttachmentsService}=require('../dist/modules/attachments/attachments.service');
const user={userId:'reader',selectedFactoryId:'factory',departmentId:'own',role:'STORE',isAdmin:false,isGuest:false,permissions:['orders.read','orders.request','orders.items.manage','orders.take']};
function fixture(type='ORDER_REQUEST'){
 const m=memory(),source={id:'source',factoryId:'factory',departmentId:'own',isActive:true,archivedAt:null,status:'ACTIVE'},attachment={id:'file',entityType:type,entityId:'source',factoryId:'factory',uploadedById:'reader',operationId:'op',kind:'PHOTO',mimeType:'image/png',originalName:'photo.png',storagePath:'private',deletedAt:null};
 const rows=[attachment],items=[source],movement={...source,itemId:'source'};
 m.data.orderRequest=m.model('orderRequest',items);m.data.minimumStockItem=m.model('minimumStockItem',items);m.data.minimumStockMovement=m.model('minimumStockMovement',[movement]);m.data.attachment=m.model('attachment',rows,{compounds:['uploadedById_operationId']});
 let reads=0,saves=0;const service=new AttachmentsService({db:m.db},{readStorageFile:async()=>{reads++;return Buffer.from('photo');},saveUploadedFile:async()=>{saves++;throw Error('Unexpected storage write');}},m.audit);
 return{...m,service,source,attachment,movement,rows,items,reads:()=>reads,saves:()=>saves};
}
test('ADMIN guest denied before bytes, even when denial audit fails',async()=>{const f=fixture();f.audit.write=async()=>{throw Error('Audit unavailable');};await assert.rejects(f.service.getFile({...user,isAdmin:true,isGuest:true},'file'),denied);assert.equal(f.reads(),0);});
for(const type of ['ORDER_REQUEST','MINIMUM_STOCK_ITEM','MINIMUM_STOCK_MOVEMENT']){
 test(type+' own/admin positive; shared/other/no-department denied before bytes',async()=>{const f=fixture(type);assert.equal((await f.service.getFile(user,'file')).buffer.toString(),'photo');for(const dept of [null,'other']){f.source.departmentId=dept;await assert.rejects(f.service.getFile(user,'file'),denied);assert.equal((await f.service.getFile({...user,isAdmin:true},'file')).buffer.toString(),'photo');}f.source.departmentId='own';await assert.rejects(f.service.getFile({...user,departmentId:null},'file'),denied);});
 test(type+' archived read retained; upload/delete denied even for ADMIN',async()=>{const f=fixture(type);f.source.status='ORDERED';f.source.isActive=false;f.source.archivedAt=new Date();assert((await f.service.getFile(user,'file')).buffer.length);for(const actor of[user,{...user,isAdmin:true}]){await assert.rejects(f.service.deactivate(actor,'file'),denied);await assert.rejects(f.service.upload(actor,{buffer:Buffer.from('photo'),originalname:'photo.png',mimetype:'image/png',size:5},{entityType:type,entityId:'source',kind:'PHOTO',operationId:'new'}),denied);}assert.equal(f.writes.length,0);assert.equal(f.saves(),0);});
 test(type+' attachment factory differs from selected/parent: deny',async()=>{const f=fixture(type);f.attachment.factoryId='foreign';await assert.rejects(f.service.getFile({...user,isAdmin:true},'file'),denied);assert.equal(f.reads(),0);});
}
test('movement parent factory authoritative even when movement factory matches selected',async()=>{const f=fixture('MINIMUM_STOCK_MOVEMENT');f.source.factoryId='foreign';await assert.rejects(f.service.getFile({...user,isAdmin:true},'file'),denied);assert.equal(f.reads(),0);});
test('replay checks stored object, not just new permitted target',async()=>{const f=fixture();f.items.push({...f.source,id:'allowed'});f.source.departmentId='revoked';const file={buffer:Buffer.from('photo'),originalname:'photo.png',mimetype:'image/png',size:5};await assert.rejects(f.service.upload(user,file,{entityType:'ORDER_REQUEST',entityId:'allowed',kind:'PHOTO',operationId:'op'}),denied);assert.equal(f.saves(),0);assert.equal(f.writes.length,0);});
test('same lawful replay returns same safe metadata without bytes/write/duplicate',async()=>{const f=fixture();const r=await f.service.upload(user,{buffer:Buffer.from('photo'),originalname:'photo.png',mimetype:'image/png',size:5},{entityType:'ORDER_REQUEST',entityId:'source',kind:'PHOTO',operationId:'op'});assert.equal(r.id,'file');assert.equal(r.storagePath,undefined);assert.equal(f.reads(),0);assert.equal(f.saves(),0);assert.equal(f.writes.length,0);});
test('internal metadata caller filters already-authorized source ids by matching factory',async()=>{const f=fixture();assert.equal((await f.service.listForEntities('ORDER_REQUEST',['source'],'factory')).get('source').length,1);f.attachment.factoryId='foreign';assert.equal((await f.service.listForEntities('ORDER_REQUEST',['source'],'factory')).size,0);assert.equal(f.reads(),0);});
