const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const ts=require('../../node_modules/typescript');
const root=path.resolve(__dirname,'../..');
const source=fs.readFileSync(path.join(root,'frontend/src/screens/ChatsScreen.tsx'),'utf8');
const ast=ts.createSourceFile('ChatsScreen.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
const functions={};function visit(node){if(ts.isVariableDeclaration(node)&&ts.isIdentifier(node.name)&&['closeChat','loadChats','openChat'].includes(node.name.text))functions[node.name.text]=node.initializer.getText(ast);ts.forEachChild(node,visit);}visit(ast);
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};}
function harness(get){const state={selected:null,chats:[],posts:[],media:null,exposed:[]};const env={Error,apiClient:{get,post:async p=>state.posts.push(p)},chatLoadVersionRef:{current:0},chatListVersionRef:{current:0},chatIntentVersionRef:{current:0},requestedChatIdRef:{current:null},chatListSignatureRef:{current:''},chatDetailSignatureRef:{current:''},chats:[{id:'A'}],selected:null,isPilotFixtureText:()=>false,chatListSignature:()=>'',chatDetailSignature:()=>'',setSelected:x=>{state.selected=x;if(x)state.exposed.push(x.id);},setChats:x=>state.chats=x,setChatMedia:x=>state.media=x};for(const x of['setModal','setParticipantProfile','setSelectedMessage','setLoading','setErrorText','setLiveStatus','setToastText'])env[x]=()=>{};
 env.setListLoading=x=>state.listLoading=x;env.setDetailLoading=x=>state.detailLoading=x;
 const code=Object.entries(functions).map(([name,fn])=>`const ${name}=${fn};`).join('\n')+'\n globalThis.api={closeChat,loadChats,openChat};';vm.runInNewContext(ts.transpileModule(code,{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS}}).outputText,env);return{...env.api,state,env};}
test('navigation uses eligibility, not broad read, and still denies guest',()=>{const text=fs.readFileSync(path.join(root,'frontend/src/navigation/permissions.ts'),'utf8');const scope={exports:{}};vm.runInNewContext(ts.transpileModule(text,{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS}}).outputText,scope);const can=scope.exports.canShowScreen;for(const role of['OTHER','CONTRACTOR_LEAD'])assert.equal(can('chats',['chats.access'],role,false),true);for(const role of['WORKER','CONTRACTOR'])assert.equal(can('chats',[],role,false),false);assert.equal(can('chats',['chats.read'],'OTHER',false),false);assert.equal(can('chats',['chats.access'],'OTHER',true),false);});
for(const mode of['list-omission','list-denial','Back'])test(`pending real-owner detail ignored after ${mode}`,async()=>{const pending=deferred();const h=harness(p=>p==='/chats/A'?pending.promise:mode==='list-denial'?Promise.reject(new Error('Нет доступных чатов.')):Promise.resolve([]));const opening=h.openChat('A');if(mode==='Back')h.closeChat();else await h.loadChats({silent:true});pending.resolve({id:'A',messages:[{text:'old'}]});await opening;assert.equal(h.state.selected,null);assert.deepEqual(h.state.exposed,[]);assert.deepEqual(h.state.posts,[]);});
test('older list omission cannot close a newer open intent',async()=>{const list=deferred(),detail=deferred();let lists=0;const h=harness(p=>p==='/chats'?(++lists===1?list.promise:Promise.resolve([{id:'B'}])):p==='/chats/B'?detail.promise:Promise.resolve({media:[],files:[]}));h.env.requestedChatIdRef.current='A';const loading=h.loadChats({silent:true});const opening=h.openChat('B');list.resolve([]);await loading;detail.resolve({id:'B',messages:[]});await opening;assert.equal(h.state.selected.id,'B');});
test('late older list cannot restore a removed row',async()=>{const old=deferred();let n=0;const h=harness(()=>++n===1?old.promise:Promise.resolve([]));const first=h.loadChats();await h.loadChats({silent:true});old.resolve([{id:'removed'}]);await first;assert.equal(h.state.chats.length,0);});
test('silent latest list completion releases read spinner while older normal request is pending',async()=>{const old=deferred();let n=0;const h=harness(()=>++n===1?old.promise:Promise.resolve([]));const first=h.loadChats();assert.equal(h.state.listLoading,true);await h.loadChats({silent:true});assert.equal(h.state.listLoading,false);old.resolve([]);await first;assert.equal(h.state.listLoading,false);});
test('silent detail supersession releases its own spinner',async()=>{const old=deferred();let n=0;const h=harness(p=>p==='/chats/A'?(++n===1?old.promise:Promise.resolve({id:'A',messages:[]})):Promise.resolve(p==='/chats'?[{id:'A'}]:{media:[],files:[]}));h.env.chats=[];const first=h.openChat('A');assert.equal(h.state.detailLoading,true);await h.openChat('A',{silent:true});assert.equal(h.state.detailLoading,false);old.resolve({id:'A',messages:[]});await first;assert.equal(h.state.detailLoading,false);});
