// Infrastructure-only memory repositories. Actual services calculate quantities and scope.
require('./master-offline-guard.cjs');require('reflect-metadata');
const {test}=require('node:test'),assert=require('node:assert/strict');
const {QuantityReleaseService}=require('../dist/common/quantity-release.service');
const {ReturnsService}=require('../dist/modules/returns/returns.service');
const {OkkService}=require('../dist/modules/okk/okk.service');
const {StockService}=require('../dist/modules/stock/stock.service');
const {OrdersService}=require('../dist/modules/orders/orders.service');
const {DefrostService}=require('../dist/modules/defrost/defrost.service');
const {WashService}=require('../dist/modules/wash/wash.service');
const {ChatsService}=require('../dist/modules/chats/chats.service');
const {AnnouncementsService}=require('../dist/modules/announcements/announcements.service');
const {UserContextService}=require('../dist/common/user-context.service');
const {AdminService}=require('../dist/modules/admin/admin.service');
const {DirectoryService}=require('../dist/modules/directory/directory.service');
const {LineService}=require('../dist/modules/line/line.service');
const {ShiftService}=require('../dist/modules/shift/shift.service');
const {ChecklistsService}=require('../dist/modules/checklists/checklists.service');
const strict=(value,label='dependency')=>new Proxy(value,{get(t,k){if(typeof k==='symbol'||k==='then')return t[k];if(!(k in t))throw Error(`UNMOCKED ${label}.${k}`);return t[k];}});
const copy=value=>{if(value===null||typeof value!=='object')return value;if(value instanceof Date)return new Date(value);if(typeof value.toDecimalPlaces==='function')return value;if(Array.isArray(value))return value.map(copy);return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,copy(v)]));};
function matches(row,where={}){return Object.entries(where).every(([k,v])=>{if(v===undefined)return true;if(k==='AND')return(Array.isArray(v)?v:[v]).every(w=>matches(row,w));if(k==='OR')return v.some(w=>matches(row,w));if(v&&typeof v==='object'&&!(v instanceof Date))return Object.entries(v).every(([op,x])=>{if(op==='in')return x.includes(row[k]);if(op==='notIn')return !x.includes(row[k]);if(op==='not')return row[k]!==x;if(op==='gte')return row[k]>=x;if(op==='lte')return row[k]<=x;if(op==='gt')return row[k]>x;if(op==='lt')return row[k]<x;if(op==='some')return row[k].some(r=>matches(r,x));if(op==='none')return !row[k].some(r=>matches(r,x));if(op==='startsWith')return String(row[k]??'').startsWith(x);if(op==='contains')return String(row[k]??'').toLowerCase().includes(String(x).toLowerCase());if(op==='mode')return true;throw Error(`UNSUPPORTED WHERE ${k}.${op}`);});return row[k]===v;});}
const actor={userId:'memory-domain-actor',selectedFactoryId:'memory-domain-factory',departmentId:'memory-department',role:'OKK',isGuest:false,isAdmin:false,permissions:['okk.manage','returns.manage','returns.publication.read']};
const failStatus=status=>error=>error.getStatus?.()===status;
function memory(){const data={},audits=[],events=[],calls=[],operations=[];let sequence=0;
 const model=(label,rows)=>strict({findFirst:async({where})=>{calls.push({label,where});return copy(rows.find(r=>matches(r,where))??null);},findUnique:async({where})=>{const match=where.userId_operationId??where;return copy(rows.find(r=>matches(r,match))??null);},findMany:async({where={},take,skip=0}={})=>{calls.push({label,where});return rows.filter(r=>matches(r,where)).slice(skip,take===undefined?undefined:skip+take).map(copy);},count:async({where})=>rows.filter(r=>matches(r,where)).length,create:async({data:input})=>{const r={id:`memory-${label}-${++sequence}`,version:0,deletedAt:null,archivedAt:null,createdAt:new Date(),...copy(input)};rows.push(r);return copy(r);},update:async({where,data:values})=>{const r=rows.find(r=>matches(r,where));assert.ok(r,`${label} update target exists`);for(const[k,v]of Object.entries(values))r[k]=v&&typeof v==='object'&&'increment'in v?r[k]+v.increment:copy(v);return copy(r);}},label);
 const db=strict(data,'db');data.$transaction=async(fn)=>fn(db); // NOT transaction rollback/concurrency emulation.
 data.$executeRaw=async(strings)=>{assert.match(strings.join('?'),/pg_advisory_xact_lock/);return 0;};data.processedOperation=model('processedOperation',operations);
 const audit=strict({write:async x=>audits.push(copy(x)),writeTx:async(_db,x)=>audits.push(copy(x))},'audit');
 const ws=strict({broadcast:(...args)=>events.push(copy(args))},'ws');const attachments=strict({listForEntities:async()=>new Map()},'attachments');return{data,db,model,audit,ws,attachments,audits,events,operations,calls};
}
test('J02 J25 real Admin create config Directory consumers deny duplicate foreign deactivate restore',async()=>{
 const m=memory(),who={...actor,role:'ADMIN',isAdmin:true},departments=[],lines=[],titles=[];
 m.data.factory=m.model('factory',[{id:who.selectedFactoryId,deletedAt:null,name:'Рабочая площадка'}]);m.data.department=m.model('department',departments);m.data.jobTitle=m.model('jobTitle',titles);
 const lineModel=m.model('line',lines);m.data.line=strict({...lineModel,create:({data})=>lineModel.create({data:{positions:[],staffingTemplates:[],...data}})});
 const admin=new AdminService({db:m.db},m.audit,m.ws,strict({}),strict({})),directory=new DirectoryService({db:m.db});
 await assert.rejects(admin.createDepartment({...who,isAdmin:false},{name:'Отдел'}),failStatus(403));await assert.rejects(admin.createDepartment(who,{name:'Отдел',factoryId:'foreign'}),failStatus(403));
 const department=await admin.createDepartment(who,{name:'Упаковка рабочая',code:'PACKING_WORK'});assert.equal((await directory.departments(who,{}))[0].id,department.id);await assert.rejects(admin.createDepartment(who,{name:'Упаковка рабочая',code:'PACKING_WORK'}),failStatus(409));assert.equal(departments.length,1);
 const title=await admin.createJobTitle(who,{name:'Оператор упаковки',code:'OPERATOR_PACK',departmentId:department.id,baseRole:'WORKER',shiftDurationHours:12});assert.equal((await admin.jobTitles(who))[0].id,title.id);assert.equal(title.departmentId,department.id);assert.equal(title.baseRole,'WORKER');
 const line=await admin.createLine(who,{name:'Упаковка пакетами'});assert.equal(line.status,'STOP');assert.equal((await directory.lines(who,{}))[0].id,line.id);await assert.rejects(admin.createLine(who,{name:'Упаковка пакетами'}),failStatus(409));await assert.rejects(directory.lines(who,{factoryId:'foreign'}),failStatus(403));
 await assert.rejects(admin.updateDepartmentStatus(who,department.id,{isActive:false,reason:''}),failStatus(409));await admin.updateDepartmentStatus(who,department.id,{isActive:false,reason:'Временная реорганизация участка'});assert.equal((await directory.departments(who,{})).length,0);await admin.updateDepartmentStatus(who,department.id,{isActive:true});assert.equal((await directory.departments(who,{}))[0].id,department.id);assert.equal(departments.length,1);assert.equal(m.audits.length,5);
});
function bulkModel(m,name,rows){const base=m.model(name,rows);return strict({...base,updateMany:async({where,data})=>{const selected=rows.filter(r=>matches(r,where));for(const row of selected)await base.update({where:{id:row.id},data});return{count:selected.length};}});}
test('J05 actual Line PAUSE preserves factual assignment STOP closes it without touching future plan',async()=>{
 const m=memory(),who={...actor,role:'MASTER'},line={id:'memory-line-status',factoryId:who.selectedFactoryId,name:'Упаковка',status:'WORK',version:0,deletedAt:null,deactivatedAt:null},events=[],assignments=[{id:'memory-fact',factoryId:who.selectedFactoryId,lineId:'memory-line-status',userId:'memory-operator',kind:'LINE',positionId:null,startedAt:new Date(),endedAt:null,version:0}],future=[{id:'memory-future-plan',userId:'memory-operator',lineId:'memory-line-status'}],users=[{id:'memory-operator',employeeState:'ASSIGNED',version:0}];
 m.data.line=bulkModel(m,'line',[line]);m.data.lineEvent=bulkModel(m,'lineEvent',events);m.data.assignment=bulkModel(m,'assignment',assignments);m.data.user=bulkModel(m,'user',users);m.data.washSession=m.model('wash',[]);m.data.defrostEvent=m.model('defrost',[]);
 // Any call to futureShiftAssignment is deliberately unmocked: STOP has no authority to erase planning.
 // ADMIN02: STOP also checks for foreign factual sessions; this fixture has none.
 m.data.shiftSession=m.model('shiftSession',[]);
 const service=new LineService({db:m.db},m.ws,m.audit,strict({}));await assert.rejects(service.updateStatus(line.id,'PAUSE','Осмотр',{...who,selectedFactoryId:'foreign'}),failStatus(409));await assert.rejects(service.updateStatus(line.id,'PAUSE','',who),failStatus(400));assert.equal(events.length,0);
 await service.updateStatus(line.id,'PAUSE','Осмотр защиты',who);assert.equal(line.status,'PAUSE');assert.equal(assignments[0].endedAt,null);assert.equal(users[0].employeeState,'ASSIGNED');assert.equal(events.length,1);
 await assert.rejects(service.updateStatus(line.id,'STOP','Остановка',who,null,{expectedVersion:0}),failStatus(409));assert.equal(assignments[0].endedAt,null);
 await service.updateStatus(line.id,'STOP','Остановка участка',who,null,{expectedVersion:line.version});assert.equal(line.status,'STOP');assert.ok(assignments[0].endedAt);assert.equal(users[0].employeeState,'AVAILABLE');assert.equal(future.length,1);assert.ok(events[0].confirmedEndAt);assert.equal(events.length,2);
 await service.updateStatus(line.id,'WORK','Запуск',who);assert.equal(events.length,3);assert.equal(users[0].employeeState,'AVAILABLE','WORK does not recreate factual assignment');assert.equal(m.audits.length,3);assert.equal(m.events.length,3);
});
test('J03 actual Shift timeline factory midnight projection planning and past permission contracts are read-only',async()=>{
 const m=memory(),who={...actor,role:'MASTER'},access={isActive:true,isGuest:false,user:{blockedAt:null,deletedAt:null}};m.data.userFactoryAccess=strict({findUnique:async({where})=>where.userId_factoryId.factoryId===who.selectedFactoryId?copy(access):null});
 const service=new ShiftService({db:m.db},strict({}),m.audit,strict({}),strict({}),m.ws);
 const timeline=await service.timeline(who,new Date('2026-09-14T21:05:00Z'));assert.equal(timeline.current.shiftType,'NIGHT');assert.equal(timeline.current.shiftDate,'2026-09-14');assert.equal(timeline.next.shiftDate,'2026-09-15');assert.equal(timeline.past.length,2);
 await assert.rejects(service.timeline({...who,isGuest:true}),failStatus(403));access.isActive=false;await assert.rejects(service.timeline(who),failStatus(403));access.isActive=true;assert.equal((await service.timeline(who)).future.length,2);
 const planned={id:'memory-plan',kind:'WORK_AREA',userId:'memory-operator',workAreaId:'memory-area',workArea:{name:'Упаковка'},workAreaPositionId:'memory-place',workAreaPosition:{title:'Оператор'},slotIndex:1};const before=JSON.stringify(planned);const projection=service.serializeFutureShiftAssignment(planned);assert.equal(projection.targetLabel,'Упаковка / Оператор / #1');assert.equal(JSON.stringify(planned),before);assert.equal(service.buildWillBeStatusByUser([{userId:'memory-operator',status:'WILL_BE'}]).get('memory-operator'),'WILL_BE');assert.throws(()=>service.ensureCanEditShiftAssignment({...who,isAdmin:false,role:'WORKER',permissions:[]},new Date('2030-01-01'),'DAY'),failStatus(403));assert.equal(m.audits.length,0);assert.equal(m.events.length,0);
});
test('J12 actual periodic Checklist pause resume close keeps occurrences and reason line guards',async()=>{
 const m=memory(),who={...actor,role:'TECH_MECHANIC',permissions:['checklists.runs.self']},line={id:'memory-check-line',factoryId:who.selectedFactoryId,name:'Упаковка',deletedAt:null,status:'WORK'},run={id:'memory-periodic',factoryId:who.selectedFactoryId,departmentId:who.departmentId,userId:who.userId,status:'ACTIVE',lineId:line.id,frequencyIntervalUnit:'HOURS',frequencyIntervalValue:2,rows:[{id:'row',status:'OK',isRequired:true}],checks:[{id:'memory-check',runId:'memory-periodic',status:'ACTIVE',rows:[{id:'occurrence-row',status:'OK',isRequired:true}]}]},pauses=[];
 m.data.line=m.model('line',[line]);m.data.checklistRun=m.model('run',[run]);m.data.checklistRunCheck=bulkModel(m,'check',run.checks);const base=m.model('pause',pauses);m.data.checklistPauseEvent=strict({...base,create:({data})=>base.create({data:{pausedAt:new Date(),resumedAt:null,...data}})});m.data.checklistSettings=strict({findUnique:async()=>({requirePauseComment:true})});
 const service=new ChecklistsService({db:m.db},m.attachments,m.audit,strict({}),m.ws);await assert.rejects(service.pause(who,run.id,{reason:''}),failStatus(409));await assert.rejects(service.pause(who,run.id,{reason:'Осмотр'}),failStatus(409));assert.equal(pauses.length,0);line.status='PAUSE';
 await service.pause(who,run.id,{reason:'Ожидание осмотра'});assert.equal(run.status,'PAUSED');assert.equal(pauses.length,1);await assert.rejects(service.resume({...who,selectedFactoryId:'foreign'},run.id),failStatus(409));await service.resume(who,run.id);assert.equal(run.status,'ACTIVE');assert.ok(pauses[0].resumedAt);await assert.rejects(service.close(who,run.id,{reason:''}),failStatus(409));
 await service.close(who,run.id,{reason:'Периодический контроль завершён'});assert.equal(run.status,'CLOSED');assert.equal(run.closeKind,'MANUAL_EARLY');assert.equal(run.checks[0].status,'CLOSED');assert.equal(run.rows[0].id,'row');assert.equal(run.checks[0].rows[0].id,'occurrence-row');await service.close(who,run.id,{reason:'Повтор'});assert.equal(m.audits.length,3);
});
for(const kind of ['OKK','RETURN'])test(`J15 J17 ${kind} actual release and publication readers agree through partial final replay denial`,async()=>{
 const m=memory();const records=[{id:`memory-${kind}`,factoryId:actor.selectedFactoryId,status:'ACTIVE',archivedAt:null,deletedAt:null,version:0,quantity:10,unit:'штуки',defectQuantity:'10 штук',createdAt:new Date(),createdBy:{id:actor.userId,role:'OKK'},description:'Проверка упаковки',productName:'Упаковка',assignedMasterId:null}];const releases=[];
 m.data[kind==='OKK'?'okkRecord':'returnRecord']=m.model(kind,records);m.data.quantityReleaseOperation=m.model('release',releases);
 m.data.userFactoryAccess=strict({findFirst:async({where})=>{assert.equal(where.factoryId,actor.selectedFactoryId);assert.equal(where.isActive,true);assert.deepEqual(where.user,{blockedAt:null,deletedAt:null});return{role:actor.role,user:{id:actor.userId},department:{name:'Контроль качества'}};}},'active access');
 const quantity=new QuantityReleaseService({db:m.db},m.audit,m.ws);
 const consumer=kind==='OKK'?new OkkService({db:m.db},m.ws,strict({}),m.audit,m.attachments,quantity):new ReturnsService({db:m.db},m.attachments,m.audit,quantity,m.ws);
 const release=(who,id,body)=>consumer.partialRelease(who,id,body);
 const list=(who=actor,archive=false)=>kind==='OKK'?consumer.listRecords(who,who.selectedFactoryId,undefined,archive):consumer.listReturns(who,who.selectedFactoryId,{includeArchive:archive});
 const body={quantity:3,comment:'Выдано после проверки',operationId:`memory-${kind}-release-a`};
 assert.equal((await list())[0].quantitySummary.remaining,'10');
 await assert.rejects(release({...actor,isGuest:true},records[0].id,body),failStatus(403));
 await assert.rejects(release({...actor,permissions:[]},records[0].id,body),failStatus(403));
 await assert.rejects(release(actor,records[0].id,{...body,quantity:11}),failStatus(409));
 if(kind==='RETURN')await assert.rejects(release(actor,records[0].id,{...body,quantity:0.5}),failStatus(409));
 assert.equal(releases.length,0);const first=await release(actor,records[0].id,body);assert.equal(first.operation.quantityAfter,'7');assert.equal(first.idempotent,false);
 assert.equal((await list())[0].releaseHistory[0].id,first.operation.id);assert.equal((await list())[0].quantitySummary.released,'3');
 assert.equal((await release(actor,records[0].id,body)).idempotent,true);assert.equal(releases.length,1);assert.equal(m.events.length,1);
 await assert.rejects(release({...actor,selectedFactoryId:'memory-foreign'},records[0].id,body),failStatus(409));
 await assert.rejects(quantity.assertOriginalQuantityMutable(m.db,kind,records[0].id),failStatus(409));
 if(kind==='RETURN'){const store={...actor,role:'STORE',permissions:['returns.publication.read']};const view=(await list(store))[0];assert.equal(view.quantitySummary.remaining,'7');assert.equal(view.quantitySummary.canRelease,false);assert.equal(view.availableActions.includes('partial-release'),false);}
 const final=await release(actor,records[0].id,{...body,quantity:7,operationId:`memory-${kind}-release-b`});assert.equal(final.archived,true);assert.equal(records[0].status,'ARCHIVED');assert.equal((await list()).length,0);
 const history=(await list(actor,true))[0];assert.equal(history.quantitySummary.remaining,'0');assert.equal(history.releaseHistory.length,2);assert.equal(history.availableActions.includes('partial-release'),false);assert.equal(m.audits.length,2);
 await assert.rejects(release(actor,records[0].id,{...body,quantity:1,operationId:`memory-${kind}-after`}),failStatus(409));assert.equal(releases.length,2);
});
test('J16 StockDefect current issue archive same record and scoped negative',async()=>{
 const m=memory(),rows=[];m.data.stockDefect=m.model('stockDefect',rows);const stock=new StockService({db:m.db},m.attachments,m.audit,m.ws);
 await assert.rejects(stock.createDefect(actor,{name:'Упаковка',quantity:0}),failStatus(409));assert.equal(rows.length,0);
 const item=await stock.createDefect(actor,{name:'Упаковка',quantity:4,unit:'шт',operationId:'memory-stock-create'});assert.equal(item.status,'ON_STOCK');assert.equal(item.unit,'штуки');
 await stock.createDefect(actor,{name:'Упаковка',quantity:4,unit:'шт',operationId:'memory-stock-create'});assert.equal(rows.length,1);
 await assert.rejects(stock.issueDefect(actor,item.id,''),failStatus(409));await assert.rejects(stock.issueDefect({...actor,selectedFactoryId:'foreign'},item.id,'Выдано'),failStatus(409));
 assert.equal((await stock.issueDefect(actor,item.id,'Выдано для переработки')).status,'ISSUED');assert.equal((await stock.listDefects(actor.selectedFactoryId))[0].id,item.id);
 await assert.rejects(stock.issueDefect(actor,item.id,'Повтор'),failStatus(409));await stock.archiveDefect(actor,item.id);assert.equal((await stock.listDefects(actor.selectedFactoryId)).length,0);assert.equal((await stock.listDefects(actor.selectedFactoryId,'ARCHIVED'))[0].quantity,4);assert.equal(m.audits.length,3);
});
test('J18 actual stock movements threshold list detail retry and STORE request boundary',async()=>{
 const m=memory(),who={...actor,role:'STORE',permissions:['orders.restock']};const rows=[{id:'memory-minimum',factoryId:who.selectedFactoryId,departmentId:who.departmentId,name:'Рабочая упаковка',currentQuantity:10,minThreshold:4,referenceQuantity:10,initialQuantity:10,unit:'шт',isActive:true,archivedAt:null,orderRequests:[],movements:[]}];const movements=[];
 const base=m.model('minimumStockItem',rows);m.data.minimumStockItem=strict({...base,findFirst:async(q)=>{const found=await base.findFirst(q);return found?{...found,movements:movements.filter(r=>r.itemId===found.id)}:null;}});m.data.minimumStockMovement=m.model('movement',movements);m.data.orderRequest=m.model('order',[]);
 m.data.orderSettings=strict({findUnique:async()=>({takeRequiresComment:true,restockRequiresComment:true,lowStockNotificationsEnabled:true})});m.data.department=strict({findMany:async({where})=>{assert.equal(where.OR[0].factoryId,who.selectedFactoryId);return[{id:who.departmentId,name:'Склад',scope:'FACTORY'}];}});
 // NOTIFY-02 supplied transaction seam; arithmetic expectations below are unchanged.
 const notices=[];const orders=new OrdersService({db:m.db},m.attachments,m.audit,strict({persistLowStockTx:async(tx,x)=>{assert.equal(tx,m.db);notices.push(copy(x));return[];},publishCommittedNotifications:async rows=>assert.equal(rows.length,0)}),m.ws);
 await assert.rejects(orders.take(who,rows[0].id,{quantity:1,comment:'',operationId:'blank'}),failStatus(409));await assert.rejects(orders.take(who,rows[0].id,{quantity:11,comment:'Расход',operationId:'over'}),failStatus(409));assert.equal(movements.length,0);
 const command={quantity:6,comment:'Расход на упаковку',operationId:'memory-take'};assert.equal((await orders.take(who,rows[0].id,command)).currentQuantity,4);assert.equal(notices.length,1);assert.equal((await orders.summary(who)).belowThreshold,1);assert.equal((await orders.items(who,{}))[0].shortageStatus,'LOW');
 await orders.take(who,rows[0].id,command);assert.equal(movements.length,1);assert.equal(notices.length,1);await assert.rejects(orders.take({...who,selectedFactoryId:'foreign'},rows[0].id,command),failStatus(409));
 const detail=await orders.item(who,rows[0].id);assert.equal(detail.movements[0].beforeQuantity,10);assert.equal(detail.movements[0].afterQuantity,4);
 await assert.rejects(orders.restock({...who,permissions:[]},rows[0].id,{quantity:2,comment:'Пополнение',operationId:'denied'}),failStatus(403));await orders.restock(who,rows[0].id,{quantity:2,comment:'Пополнение',operationId:'memory-restock'});assert.equal((await orders.items(who,{}))[0].currentQuantity,6);assert.equal(movements.length,2);
 assert.throws(()=>orders.assertCanRequest(who),failStatus(403));assert.doesNotThrow(()=>orders.assertCanRequest({...who,permissions:[...who.permissions,'orders.request']}));assert.throws(()=>orders.assertRequestManager({...who,permissions:['orders.request']}),failStatus(403));
});
test('J11 actual Defrost start end calendar line invalidation and forbidden WORK or Wash overlap',async()=>{
 const m=memory(),who={...actor,role:'TECH_HOLOD',permissions:['defrost.manage']};const line={id:'memory-cold-line',name:'Камера охлаждения',factoryId:who.selectedFactoryId,status:'WORK',deletedAt:null,deactivatedAt:null};const events=[],washes=[];
 m.data.line=m.model('line',[line]);const eventModel=m.model('defrost',events);m.data.defrostEvent=strict({...eventModel,create:q=>eventModel.create({...q,data:{status:'ACTIVE',durationSeconds:null,endAt:null,...q.data}})});m.data.washSession=m.model('wash',washes);m.data.defrostSettings=strict({findUnique:async()=>({defrostCommentRequiredOnStart:true,defrostCommentRequiredOnEnd:true})});
 const notices=[];const defrost=new DefrostService({db:m.db},m.audit,strict({notifyDefrost:async(e,type)=>notices.push({id:e.id,type})}),m.ws,strict({}));const command={lineId:line.id,comment:'Плановая оттайка',operationId:'memory-defrost-start'};
 await assert.rejects(defrost.start(who,command),failStatus(409));line.status='STOP';washes.push({id:'ordinary-active-wash',factoryId:who.selectedFactoryId,lineId:line.id,status:'IN_PROGRESS'});await assert.rejects(defrost.start(who,command),failStatus(409));washes[0].status='DONE';
 const started=await defrost.start(who,command);assert.equal(started.status,'ACTIVE');assert.equal((await defrost.list(who))[0].id,started.id);assert.equal((await defrost.calendar(who))[0].events[0].id,started.id);
 await assert.rejects(defrost.detail({...who,permissions:[]},started.id),failStatus(403));await assert.rejects(defrost.detail({...who,isGuest:true},started.id),failStatus(403));await assert.rejects(defrost.detail({...who,selectedFactoryId:'foreign'},started.id),failStatus(409));
 await defrost.start(who,command);assert.equal(events.length,1);await assert.rejects(defrost.start(who,{...command,operationId:'memory-defrost-second'}),failStatus(409));
 await assert.rejects(defrost.end(who,started.id,{comment:'',operationId:'memory-defrost-end'}),failStatus(409));const endCommand={comment:'Лёд удалён',operationId:'memory-defrost-end'};const ended=await defrost.end(who,started.id,endCommand);assert.equal(ended.status,'COMPLETED');assert.ok(ended.durationSeconds>=0);assert.equal((await defrost.detail(who,ended.id)).endComment,'Лёд удалён');await defrost.end(who,started.id,endCommand);assert.equal(m.operations.length,2);
 assert.ok(m.events.some(([,payload])=>payload.id===line.id&&payload.sourceId===started.id));assert.ok(notices.some(n=>n.id===started.id&&n.type==='DEFROST_COMPLETED'));assert.equal(line.status,'STOP','end does not silently restart WORK');
 // Replays intentionally may emit invalidation/notification adapter calls again; no exactly-once fanout claim.
});
test('J10 actual Wash request take start comment completion preserves linked request and participant history',async()=>{
 const m=memory(),who={...actor,role:'MASTER',permissions:['wash.read','wash.manage']};const line={id:'memory-wash-line',factoryId:who.selectedFactoryId,name:'Линия упаковки',status:'STOP',deletedAt:null,deactivatedAt:null};const worker={id:'memory-wash-worker',factoryId:who.selectedFactoryId,employeeState:'ASSIGNED',version:0,blockedAt:null,deletedAt:null};const manager={id:who.userId,factoryId:who.selectedFactoryId,role:who.role,blockedAt:null,deletedAt:null};const users=[worker,manager],requests=[],sessions=[],messages=[],history=[],assignments=[{id:'memory-line-assignment',factoryId:who.selectedFactoryId,userId:worker.id,lineId:line.id,kind:'LINE',startedAt:new Date(),endedAt:null,version:0}];
 const withBulk=(name,rows)=>{const base=m.model(name,rows);return strict({...base,updateMany:async({where,data})=>{const matched=rows.filter(r=>matches(r,where));for(const row of matched)await base.update({where:{id:row.id},data});return{count:matched.length};},createMany:async({data})=>{for(const r of data)await base.create({data:{endedAt:null,...r}});return{count:data.length};}});};
 m.data.line=m.model('line',[line]);m.data.user=withBulk('user',users);m.data.assignment=withBulk('assignment',assignments);m.data.washControlItem=withBulk('control',requests);m.data.washMessage=m.model('message',messages);m.data.washEvent=m.model('washEvent',history);m.data.shiftSession=m.model('shift',[]);m.data.defrostEvent=m.model('defrost',[]);
 // ADMIN02: transfer to wash now honours canonical sent-home provenance.
 // No such provenance exists in this fixture; lifecycle expectations stay intact.
 m.data.auditLog=m.model('auditLog',[]);m.data.shiftReturnRequest=m.model('shiftReturnRequest',[]);
 m.data.userFactoryAccess=strict({findUnique:async({where})=>where.userId_factoryId.factoryId===who.selectedFactoryId?{isActive:true,isGuest:false,user:manager}:null,findFirst:async({where})=>where.factoryId===who.selectedFactoryId?{isActive:true,isGuest:false}:null});
 const base=withBulk('washSession',sessions);const enrich=r=>r?{...r,line,assignments:assignments.filter(a=>a.washSessionId===r.id).map(a=>({...a,user:worker})),messages:messages.filter(a=>a.washSessionId===r.id),events:history.filter(a=>a.washSessionId===r.id),issues:[],controlItems:[],okkReviews:[]}:null;
 m.data.washSession=strict({...base,findUnique:async q=>enrich(await base.findUnique(q)),findFirst:async q=>enrich(await base.findFirst(q)),findMany:async q=>(await base.findMany(q)).map(enrich)});m.data.washSettings=strict({findUnique:async()=>({washCompleteRequiresNoOpenIssues:false,washCompleteRequiresOkkReview:false})});
 const wash=new WashService({db:m.db},m.ws,m.audit,m.attachments,strict({}));const input={lineId:line.id,description:'Помыть оборудование после смены',operationId:'memory-wash-request'};
 await assert.rejects(wash.createRequest({...who,permissions:['wash.read']},input),failStatus(403));const request=await wash.createRequest(who,input);assert.equal(request.status,'NEW');assert.equal(sessions.length,0);await assert.rejects(wash.startRequest(who,request.id,{operationId:'memory-wash-start'}),failStatus(409));
 await assert.rejects(wash.takeRequest(who,request.id,{version:999}),failStatus(409));await wash.takeRequest(who,request.id,{version:0});assert.equal(requests[0].status,'IN_PROGRESS');assert.equal(sessions.length,0);await assert.rejects(wash.takeRequest({...who,userId:'other-manager'},request.id,{}),failStatus(409));
 const started=await wash.startRequest(who,request.id,{operationId:'memory-wash-start',version:1});assert.equal(started.status,'WASH_STARTED');assert.equal(sessions.length,1);assert.equal(worker.employeeState,'WASHING');assert.equal(assignments.filter(a=>a.kind==='LINE'&&a.endedAt===null).length,0);assert.equal(assignments.filter(a=>a.kind==='WASH'&&a.endedAt===null).length,1);
 await wash.startRequest(who,request.id,{operationId:'memory-wash-start',version:1});assert.equal(sessions.length,1);const detail=await wash.detail(who,started.washSessionId);assert.equal(detail.participants[0].userId,worker.id);assert.equal(detail.messages.length,0,'internal WASHERS marker not shown as comment');
 await wash.addMessage(started.washSessionId,who.userId,'Проверили чистоту','memory-wash-comment',who.selectedFactoryId);assert.equal((await wash.detail(who,started.washSessionId)).messages[0].message,'Проверили чистоту');await assert.rejects(wash.detail({...who,selectedFactoryId:'foreign'},started.washSessionId),failStatus(409));
 await wash.completeWash(started.washSessionId,who.userId,who.selectedFactoryId,'memory-wash-complete');assert.equal(requests[0].status,'DONE');assert.equal(worker.employeeState,'AVAILABLE');assert.equal((await wash.list(who)).length,0);const archived=(await wash.list(who,{includeCompleted:'true'}))[0];assert.equal(archived.participants.length,0);assert.equal(archived.participantsHistory[0].userId,worker.id);assert.equal(archived.lifecycleStatus,'COMPLETED');assert.equal(line.status,'STOP');
});
test('J01 J02 actual UserContext resolves UFA role overrides blocked revoked guest and factory deactivation',async()=>{
 const access={factoryId:actor.selectedFactoryId,isActive:true,isGuest:false,role:'TECH_MECHANIC',departmentId:actor.departmentId,department:{scope:'FACTORY'},companyId:null,factory:{isActive:true,deletedAt:null}};
 const user={id:actor.userId,deletedAt:null,blockedAt:null,passwordResetRequired:false,factoryAccess:[access],permissionOverrides:[{factoryId:actor.selectedFactoryId,permissionCode:'tasks.take',effect:'DENY'},{factoryId:null,permissionCode:'tasks.comment',effect:'ALLOW'},{factoryId:'other',permissionCode:'tasks.done',effect:'ALLOW'}]};
 let reads=0;const authority=new UserContextService({db:strict({user:strict({findUnique:async({where,include})=>{reads++;assert.equal(where.id,actor.userId);assert.equal(include.factoryAccess.where.isActive,true);return{...copy(user),factoryAccess:user.factoryAccess.filter(a=>a.factoryId===include.factoryAccess.where.factoryId&&a.isActive).map(copy)};}}),rolePermission:strict({findMany:async()=>['tasks.read','tasks.take'].map(permissionCode=>({permissionCode}))})})});
 // Only this process bypasses DEV fallback to exercise the real resolver with an injected repository.
 // Prisma construction, sockets, HTTP, bootstrap and timers remain hard-blocked by preloaded guard.
 const previous={disabled:process.env.DISABLE_DB,dev:process.env.DEV_MODE};process.env.DISABLE_DB='false';process.env.DEV_MODE='false';
 try{const current=await authority.resolveForFactory(actor.userId,actor.selectedFactoryId);assert.equal(current.isGuest,false);assert.ok(current.permissions.includes('tasks.read'));assert.ok(current.permissions.includes('tasks.comment'));assert.equal(current.permissions.includes('tasks.take'),false);assert.equal(current.permissions.includes('tasks.done'),false);
 for(const scenario of ['blocked','deleted','reset','revoked','factory-inactive','factory-deleted','guest','foreign']){user.blockedAt=scenario==='blocked'?new Date():null;user.deletedAt=scenario==='deleted'?new Date():null;user.passwordResetRequired=scenario==='reset';access.isActive=scenario!=='revoked';access.factory.isActive=scenario!=='factory-inactive';access.factory.deletedAt=scenario==='factory-deleted'?new Date():null;access.isGuest=scenario==='guest';const result=await authority.resolveForFactory(actor.userId,scenario==='foreign'?'foreign':actor.selectedFactoryId);assert.equal(result.isGuest,true,scenario);assert.deepEqual(result.permissions,[],scenario);}
 assert.equal(reads,9);
 }finally{if(previous.disabled===undefined)delete process.env.DISABLE_DB;else process.env.DISABLE_DB=previous.disabled;if(previous.dev===undefined)delete process.env.DEV_MODE;else process.env.DEV_MODE=previous.dev;}
});
for(const archiveCapability of [false,true])test(`J19 publication ack report archive identity; archive capability=${archiveCapability}${archiveCapability?' KNOWN_NEGATIVE_MI-PUB-01':''}`,async()=>{
 const m=memory(),who={...actor,role:'MANAGEMENT',permissions:['announcements.create','announcements.manage','announcements.read',...(archiveCapability?['announcements.archive.read']:[])]};const announcements=[],reads=[],notices=[];const account={id:who.userId,role:who.role,blockedAt:null,deletedAt:null};
 const enrich=r=>r?{...r,author:account,department:{id:who.departmentId,name:'Производство'},audienceDepartments:[],reads:reads.filter(x=>x.announcementId===r.id)}:null;const base=m.model('announcement',announcements);
 m.data.announcement=strict({...base,create:async q=>enrich(await base.create({...q,data:{...q.data,audienceDepartments:[]}})),findFirst:async q=>announcements.map(enrich).find(r=>matches(r,q.where))??null,findMany:async q=>announcements.map(enrich).filter(r=>matches(r,q.where))});const readBase=m.model('read',reads);m.data.announcementRead=strict({...readBase,findUnique:q=>readBase.findUnique({where:q.where.announcementId_userId}),create:q=>readBase.create({...q,data:{readAt:new Date(),...q.data}})});
 m.data.user=m.model('user',[account]);m.data.announcementSettings=strict({findUnique:async()=>({defaultVisibleDays:7,importantBadgeEnabled:true,guestCanRead:false})});m.data.userFactoryAccess=strict({findMany:async({where})=>{assert.equal(where.factoryId,who.selectedFactoryId);assert.equal(where.isActive,true);assert.deepEqual(where.user,{blockedAt:null,deletedAt:null});return[{userId:who.userId,role:who.role,user:account,department:{name:'Производство'}}];}});
 const notification=strict({createForDepartment:async(factory,department,input)=>notices.push({factory,department,...input}),markEntityNotificationsRead:async(_actor,type,id)=>{for(const n of notices.filter(n=>n.entityId===id&&n.entityType===type))n.read=true;}});
 const service=new AnnouncementsService({db:m.db},m.audit,m.attachments,notification,strict({canonicalDepartments:async()=>[{id:who.departmentId,name:'Производство'}]}));
 const input={title:'Проверка оборудования',text:'Проверить защиту перед сменой',priority:'IMPORTANT',audienceType:'MY_DEPARTMENT'};
 await assert.rejects(service.create({...who,isGuest:true},input),failStatus(403));const item=await service.create(who,input);assert.equal(notices[0].entityId,item.id);assert.equal((await service.current(who)).total,1);
 await assert.rejects(service.markRead({...who,departmentId:'foreign-department'},item.id),failStatus(403));await assert.rejects(service.detail({...who,selectedFactoryId:'foreign'},item.id),failStatus(403));assert.equal(reads.length,0);
 const first=await service.markRead(who,item.id);assert.ok(first.acknowledgedAt);await service.markRead(who,item.id);assert.equal(reads.length,1);assert.equal(notices[0].read,true);assert.equal((await service.ackReport(who,item.id)).totals.acknowledged,1);
 await service.archive(who,item.id);assert.equal((await service.list(who)).length,0);assert.equal((await service.archiveList(who))[0].id,item.id);assert.equal((await service.ackReport(who,item.id)).totals.acknowledged,1);
 account.blockedAt=new Date();await assert.rejects(service.archiveList(who),failStatus(403));
});
test('J20 actual custom chat membership message reply edit delete reaction poll and unread chain',async()=>{
 const m=memory(),owner={...actor,role:'MANAGEMENT',permissions:['chats.read','chats.write','chats.manage']},member={...actor,userId:'memory-chat-member',role:'WORKER',permissions:['chats.read','chats.write']};const chats=[],members=[],messages=[],reactions=[],reads=[],polls=[],votes=[];
 const compound=where=>where.authorId_operationId??where.chatId_userId??where.messageId_userId_emoji??where.optionId_userId??where;
 const wrap=(name,rows)=>{const base=m.model(name,rows);return strict({...base,findUnique:q=>base.findUnique({...q,where:compound(q.where)}),updateMany:async({where,data})=>{const found=rows.filter(r=>matches(r,where));for(const row of found)await base.update({where:{id:row.id},data});return{count:found.length};}});};
 const userFor=id=>({id,role:id===owner.userId?owner.role:member.role,blockedAt:null,deletedAt:null});const memberBase=wrap('member',members);m.data.chatMember=strict({...memberBase,create:q=>memberBase.create({...q,data:{leftAt:null,removedAt:null,roleCode:null,departmentId:null,...q.data,user:userFor(q.data.userId)}})});
 const chatBase=wrap('chat',chats);const enrichChat=r=>r?{...r,members:members.filter(x=>x.chatId===r.id),messages:messages.filter(x=>x.chatId===r.id&&!x.deletedAt).slice(-1),reads:reads.filter(x=>x.chatId===r.id)}:null;m.data.chat=strict({...chatBase,create:q=>chatBase.create({...q,data:{isActive:true,isHidden:false,...q.data}}),findUnique:async q=>enrichChat(await chatBase.findUnique(q)),findFirst:async q=>enrichChat(await chatBase.findFirst(q)),findMany:async q=>(await chatBase.findMany(q)).map(enrichChat)});
 m.data.chatMessage=wrap('message',messages);m.data.chatMessageReaction=wrap('reaction',reactions);const readBase=wrap('chatRead',reads);m.data.chatRead=strict({...readBase,upsert:async({where,update,create})=>{const prior=await readBase.findUnique({where});return prior?readBase.update({where:{id:prior.id},data:update}):readBase.create({data:{lastReadAt:new Date(),...create}});}});
 const voteBase=wrap('vote',votes);m.data.chatPollVote=voteBase;const pollBase=wrap('poll',polls);const enrichPoll=r=>r?{...r,votes:votes.filter(x=>x.pollId===r.id),options:r.options.map(o=>({...o,votes:votes.filter(v=>v.optionId===o.id).map(v=>({...v,user:userFor(v.userId)}))}))}:null;
 m.data.chatPoll=strict({...pollBase,create:async q=>enrichPoll(await pollBase.create({...q,data:{isActive:true,...q.data,options:q.data.options.create.map((o,i)=>({...o,id:`memory-option-${i}`}))}})),findUnique:async q=>enrichPoll(await pollBase.findUnique(q)),findFirst:async q=>enrichPoll(await pollBase.findFirst(q)),findMany:async q=>(await pollBase.findMany(q)).map(enrichPoll)});
 m.data.chatSettings=strict({findUnique:async()=>({chatEnabled:true,editWindowMinutes:15,deleteWindowMinutes:15})});m.data.userFactoryAccess=strict({findMany:async({where})=>{assert.equal(where.factoryId,owner.selectedFactoryId);return where.userId.in.map(userId=>({userId,user:userFor(userId),role:userFor(userId).role,department:{name:'Производство'}}));}});const delivery=[];
 const service=new ChatsService({db:m.db},m.audit,strict({listForEntities:async(_t,ids)=>new Map(ids.map(id=>[id,[{id:`memory-attachment-${id}`,mimeType:'audio/webm',originalName:'Голосовое сообщение'}]]))}),strict({sendToUsers:(...a)=>delivery.push(a)}));
 const group=await service.create(owner,{type:'CUSTOM',title:'Передача смены',members:[{userId:member.userId,canRead:true,canWrite:true}]});assert.equal(members.filter(x=>x.membershipRole==='OWNER').length,1);
 await assert.rejects(service.createMessage({...member,selectedFactoryId:'foreign'},group.id,{text:'Нет доступа'}),failStatus(403));await assert.rejects(service.transferOwnership(member,group.id,{userId:owner.userId}),failStatus(403));
 const sent=await service.createMessage(owner,group.id,{text:'Проверить оборудование',operationId:'memory-chat-send'});await service.createMessage(owner,group.id,{text:'Проверить оборудование',operationId:'memory-chat-send'});assert.equal(messages.length,1);await assert.rejects(service.updateMessage(member,group.id,sent.id,{text:'Чужая правка'}),failStatus(403));
 await service.updateMessage(owner,group.id,sent.id,{text:'Оборудование проверено'});const reply=await service.createMessage(member,group.id,{text:'Подтверждаю',replyToMessageId:sent.id,operationId:'memory-chat-reply'});await service.toggleReaction(member,group.id,sent.id,{emoji:'✅'});assert.equal(reactions.length,1);
 let detail=await service.detail(member,group.id);assert.equal(detail.messages.find(x=>x.id===reply.id).replyTo.text,'Оборудование проверено');assert.equal(detail.messages.find(x=>x.id===sent.id).reactions[0].count,1);assert.equal(detail.messages.find(x=>x.id===sent.id).attachments[0].mimeType,'audio/webm');
 await service.deleteMessage(owner,group.id,sent.id);detail=await service.detail(member,group.id);assert.equal(detail.messages.find(x=>x.id===sent.id).text,'Сообщение удалено');assert.deepEqual(detail.messages.find(x=>x.id===sent.id).attachments,[]);assert.equal(detail.messages.find(x=>x.id===reply.id).replyTo.deleted,true);
 const poll=await service.createPoll(owner,group.id,{question:'Когда проверить узел?',options:['До смены','После смены'],anonymous:true,preventRevote:true,operationId:'memory-chat-poll'});await assert.rejects(service.votePoll(member,group.id,poll.poll.id,{optionId:'foreign-option'}),failStatus(409));const voted=await service.votePoll(member,group.id,poll.poll.id,{optionId:poll.poll.options[0].id});assert.equal(voted.votersCount,1);assert.deepEqual(voted.options[0].users,[]);await service.votePoll(member,group.id,poll.poll.id,{optionId:poll.poll.options[0].id});assert.equal(votes.length,1);await assert.rejects(service.votePoll(member,group.id,poll.poll.id,{optionId:poll.poll.options[1].id}),failStatus(409));
 await service.transferOwnership(owner,group.id,{userId:member.userId,operationId:'memory-owner-transfer'});assert.equal(members.filter(x=>x.membershipRole==='OWNER').length,1);assert.equal(members.find(x=>x.membershipRole==='OWNER').userId,member.userId);
 await service.markRead(member,group.id);assert.equal(await service.unreadCount(member,group.id,new Date()),0);members.find(x=>x.userId===owner.userId).removedAt=new Date();await assert.rejects(service.detail(owner,group.id),failStatus(403));assert.ok(delivery.length>0);
});
