require('./master-offline-guard.cjs');
const {test}=require('node:test'),assert=require('node:assert/strict');
const {gates,digest,authorize,execute}=require('./master-r3-live-gate.cjs');
const stamp=()=>new Date('2030-01-01T12:00:00Z').getTime();
function fixture(){const approved={purpose:'ZAVOD_SYNTHETIC_INTEGRATION_ONLY',environmentId:'r3-isolated-'+'a'.repeat(32),databaseMode:'DEDICATED_SYNTHETIC',egress:'DENIED',push:'DISABLED',smtp:'DISABLED',sms:'DISABLED',scheduler:'DISABLED_BEFORE_BOOTSTRAP',origin:'http://127.0.0.1:49170/',factoryIds:['r3-fixture-factory-a','r3-fixture-factory-b'],userIds:['r3-fixture-reader'],fileIds:['r3-fixture-image'],forbiddenIdentityHashes:['1'.repeat(64),'2'.repeat(64),'3'.repeat(64)],expiresAt:'2030-01-01T12:30:00Z'};for(const [i,key]of ['databaseIdentitySha256','dataDirectorySha256','fileRootSha256','serverConfigurationSha256','productFingerprint','schemaSha256','adapterSha256'].entries())approved[key]=(i+4).toString(16).repeat(64);return{approved,observed:{...approved,observedAt:'2030-01-01T12:00:00Z'},intent:{mode:'EXPLICIT_FUTURE_EXECUTION',gate:'MI-SEC-01',now:stamp(),environmentId:approved.environmentId,adapterSha256:approved.adapterSha256,approvalDigest:digest(approved)}};}
test('R3-G plan names all five gates plus exact read-only014 without opening a connection',()=>assert.deepEqual(Object.keys(gates),['MI-SEC-01','MI-PUB-01','MI-R2-ORD-01','MI-R2-CHAT-ATT-01','036','014-READONLY']));
test('R3-G authorization accepts only exact freshly observed isolated identity (guard only)',()=>{const f=fixture();assert.equal(authorize(f.intent,f.approved,f.observed).gate,'MI-SEC-01');});
for(const scenario of ['boolean','digest','observed-database','working-origin','working-identity','expired','stale','egress','scheduler','empty-fixtures','credentials-in-url','014-working-history'])test(`R3-G zero-network safety guard denies ${scenario}`,()=>{
 const f=fixture();if(scenario==='boolean')f.intent.mode=true;if(scenario==='digest')f.intent.approvalDigest='true';if(scenario==='observed-database')f.observed.databaseIdentitySha256='9'.repeat(64);if(scenario==='working-origin')f.approved.origin='http://127.0.0.1:3000/';if(scenario==='working-identity')f.approved.forbiddenIdentityHashes.push(f.approved.databaseIdentitySha256);if(scenario==='expired')f.intent.now+=3600001;if(scenario==='stale')f.observed.observedAt='2030-01-01T11:55:00Z';if(scenario==='egress')f.approved.egress='ALLOWED';if(scenario==='scheduler')f.approved.scheduler='ENABLED';if(scenario==='empty-fixtures')f.approved.factoryIds=[];if(scenario==='credentials-in-url')f.approved.origin='http://name:synthetic@127.0.0.1:49170/';if(scenario==='014-working-history')f.intent.gate='014-READONLY';assert.throws(()=>authorize(f.intent,f.approved,f.observed));
});
test('R3-G adapter object cannot self-assert its source hash and run fixtures',async()=>{const f=fixture();let runs=0;await assert.rejects(execute(f.intent,f.approved,{sourceSha256:f.approved.adapterSha256,observeIdentity:async()=>f.observed,runNamedGate:async()=>{runs++;}}));assert.equal(runs,0);});
test('R3-G arbitrary adapter source cannot execute without approved actual file hash',async()=>{const f=fixture();await assert.rejects(execute(f.intent,f.approved,__filename),/Reviewed adapter bytes/);});
test('R3-G omitted explicit execution never invokes identity adapter',async()=>{let observed=0;await assert.rejects(execute({},null,{observeIdentity:async()=>{observed++;}}));assert.equal(observed,0);});
