const assert=require('node:assert/strict'),test=require('node:test'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
function load(file){const source=fs.readFileSync(file,'utf8'),m={exports:{}};const output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(output,{module:m,exports:m.exports,crypto:require('node:crypto').webcrypto,require:name=>load(path.resolve(path.dirname(file),name+'.ts'))},{filename:file});return m.exports;}
const {duplicateChecklistItem,setChecklistItemActive}=load(path.resolve(__dirname,'../src/components/checklist-item-draft.ts'));
const file={name:'bounded.png'},saved={id:'saved-reference'},source={id:'row-original',clientKey:'original',title:'Контроль',sortOrder:10,isActive:true,referenceFile:file,referencePhoto:saved,referenceOperationId:'original-operation',removeReference:false,requiredAnswer:true};
test('copy of pending reference has its own row and upload operation identity',()=>{const a=duplicateChecklistItem(source,'copy-a',20),b=duplicateChecklistItem(source,'copy-b',30);assert.equal(a.id,undefined);assert.equal(a.referenceFile,file);assert.notEqual(a.referenceOperationId,source.referenceOperationId);assert.notEqual(a.referenceOperationId,b.referenceOperationId);assert.equal(a.referencePhoto,null);assert.equal(source.referencePhoto,saved);});
test('copy never claims inheritance of an already saved reference',()=>{const copy=duplicateChecklistItem({...source,referenceFile:null},'copy',20);assert.equal(copy.referencePhoto,null);assert.equal(copy.referenceOperationId,undefined);});
test('deactivation discards pending upload/removal, preserves saved immutable reference',()=>{const result=setChecklistItemActive({...source,removeReference:true},false);assert.equal(result.isActive,false);assert.equal(result.referenceFile,null);assert.equal(result.referenceOperationId,undefined);assert.equal(result.removeReference,false);assert.equal(result.referencePhoto,saved);assert.equal(source.isActive,true);});
test('reactivation cannot resurrect a discarded pending upload',()=>{const result=setChecklistItemActive(setChecklistItemActive(source,false),true);assert.equal(result.referenceFile,null);assert.equal(result.referenceOperationId,undefined);assert.equal(result.referencePhoto,saved);});
test('inactive copied draft has no pending file operation',()=>{const result=duplicateChecklistItem({...source,isActive:false},'copy',20);assert.equal(result.referenceFile,null);assert.equal(result.referenceOperationId,undefined);assert.equal(result.isActive,false);});
