const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const source=fs.readFileSync(path.join(__dirname,'../src/screens/ChecklistsScreen.tsx'),'utf8'),start=source.indexOf('  const uploadFiles = async ('),end=source.indexOf('\n  const rowNormText',start);assert(start>0&&end>start);
function harness(){const calls=[],seen=new Set();let fail=false,id=0;const context={rowUploadOperationsRef:{current:new WeakMap()},crypto:{randomUUID:()=>`upload-${++id}`},uploadAttachments:async(type,target,files,opts)=>{calls.push({type,target,files,ids:[...opts.operationIds]});for(const key of opts.operationIds)seen.add(key);if(fail){fail=false;throw new Error('response lost after commit');}}};vm.runInNewContext(ts.transpileModule(source.slice(start,end)+'\nglobalThis.upload=uploadFiles;',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,context);return{upload:context.upload,calls,seen,loseNext:()=>{fail=true;}};}
test('lost response keeps upload identity on same selected File and row',async()=>{const h=harness(),f={};h.loseNext();await assert.rejects(h.upload('CHECKLIST_RUN_ROW','row-a',[f]));await h.upload('CHECKLIST_RUN_ROW','row-a',[f]);assert.deepEqual(h.calls[0].ids,h.calls[1].ids);assert.equal(h.seen.size,1);});
test('multi-file retry preserves every committed file identity',async()=>{const h=harness(),files=[{},{}];h.loseNext();await assert.rejects(h.upload('CHECKLIST_ENTRY','entry-a',files));await h.upload('CHECKLIST_ENTRY','entry-a',files);assert.deepEqual(h.calls[0].ids,h.calls[1].ids);assert.equal(h.seen.size,2);});
test('same file selected for different row gets distinct intent',async()=>{const h=harness(),f={};await h.upload('CHECKLIST_RUN_ROW','a',[f]);await h.upload('CHECKLIST_RUN_ROW','b',[f]);assert.notEqual(h.calls[0].ids[0],h.calls[1].ids[0]);});
test('entity type is part of identity',async()=>{const h=harness(),f={};await h.upload('CHECKLIST_RUN_ROW','a',[f]);await h.upload('CHECKLIST_ENTRY','a',[f]);assert.notEqual(h.calls[0].ids[0],h.calls[1].ids[0]);});
test('replacing File with same metadata creates new intent',async()=>{const h=harness();await h.upload('CHECKLIST_RUN_ROW','a',[{name:'photo.png',size:10}]);await h.upload('CHECKLIST_RUN_ROW','a',[{name:'photo.png',size:10}]);assert.notEqual(h.calls[0].ids[0],h.calls[1].ids[0]);});
test('removing first file does not change retry key of second file',async()=>{const h=harness(),a={},b={};await h.upload('CHECKLIST_RUN_ROW','a',[a,b]);await h.upload('CHECKLIST_RUN_ROW','a',[b]);assert.equal(h.calls[0].ids[1],h.calls[1].ids[0]);});
