const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript'),vm=require('node:vm');
const source=fs.readFileSync(path.resolve(__dirname,'../src/screens/AdminConfigScreen.tsx'),'utf8');
function harness(){const block=source.slice(source.indexOf('  const openProfile = async'),source.indexOf('  const saveIdentity = async'));assert(block.includes('profileRequestRef'));const state={profile:{id:'old'},loading:false,form:{lastName:'old'},error:null},pending=[],ref={current:0};const ctx={profileRequestRef:ref,apiClient:{get:()=>new Promise((resolve,reject)=>pending.push({resolve,reject}))},setSelectedProfile:x=>state.profile=x,setProfileLoading:x=>state.loading=x,setIdentityForm:x=>state.form=x,setErrorText:x=>state.error=x,setNoticeText:()=>{},setIdentityError:()=>{},errorMessage:e=>e.message};const js=ts.transpileModule(`${block}\nglobalThis.open=openProfile;`,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(js,ctx);return{state,pending,ref,open:ctx.open};}
test('pending profile removes previous editable identity immediately',async()=>{const h=harness(),p=h.open('next');assert.equal(h.state.profile,null);assert.equal(h.state.loading,true);h.pending[0].resolve({id:'next',lastName:'Next'});await p;assert.equal(h.state.profile.id,'next');assert.equal(h.state.form.lastName,'Next');assert.equal(h.state.loading,false);});
test('out-of-order GET cannot replace the last chosen person or draft',async()=>{const h=harness(),a=h.open('A'),b=h.open('B');h.pending[1].resolve({id:'B',lastName:'B'});await b;h.pending[0].resolve({id:'A',lastName:'A'});await a;assert.equal(h.state.profile.id,'B');assert.equal(h.state.form.lastName,'B');});
test('late failure cannot stop a newer load or show stale error',async()=>{const h=harness(),a=h.open('A'),b=h.open('B');h.pending[0].reject(new Error('old'));await a;assert.equal(h.state.loading,true);assert.equal(h.state.error,null);h.pending[1].resolve({id:'B'});await b;assert.equal(h.state.loading,false);});
test('scope/unmount generation invalidates pending success',async()=>{const h=harness(),p=h.open('A');h.ref.current++;h.pending[0].resolve({id:'A'});await p;assert.equal(h.state.profile,null);});
test('current failure leaves no previous editable identity',async()=>{const h=harness(),p=h.open('A');h.pending[0].reject(new Error('denied'));await p;assert.equal(h.state.profile,null);assert.equal(h.state.loading,false);assert.equal(h.state.error,'denied');});
test('render and save preserve loading/busy identity boundary',()=>{assert.match(source,/selectedProfile && !profileLoading \? \(/);assert.match(source,/if \(!selectedProfile \|\| profileLoading \|\| busy\) return/);assert.match(source,/disabled=\{busy\} onClick=\{\(\) => void openProfile\(user.id\)\}/);assert.match(source,/if \(request === profileRequestRef.current\) await openProfile\(selectedProfile.id\)/);});
