const{test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const source=fs.readFileSync(path.resolve(__dirname,'../src/App.tsx'),'utf8'),ast=ts.createSourceFile('App.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let initializer;
function visit(n){if(ts.isVariableDeclaration(n)&&n.name.getText(ast)==='navigateNotificationSource')initializer=n.initializer.getText(ast);ts.forEachChild(n,visit);}visit(ast);assert(initializer);
function fixture({notification={},allowed=true,current=()=>true,readError=false}={}){const calls=[],pending=[];const me={userId:'u',selectedFactoryId:'f',isGuest:false,availableFactories:[{id:'f'}],permissions:['tasks.read'],role:'TECH_KIPIA'};
 const scope={exports:{},selectedFactoryId:'f',SCREEN_DEFINITIONS:[{code:'tasks',id:'Tasks'},{code:'orders',id:'Orders'}],apiClient:{request:async(url)=>{calls.push(url);if(url.startsWith('/notifications/')&&url.endsWith('/read')){if(readError)throw Error('FORBIDDEN');return{factoryId:'f',entityType:'TASK',entityId:'task-from-server',...notification};}if(url==='/auth/me')return me;return{count:0};}},appStore:{setNotificationsUnreadCount:()=>{},setSession:()=>{}},asyncContextEpoch:{current:8},setPendingNotificationScreen:x=>pending.push(x),canShowScreen:()=>allowed,hasDirtyMobileForms:()=>false,toCurrentUser:x=>x};
 vm.runInNewContext(ts.transpileModule('exports.navigate='+initializer,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,scope);
 return{calls,pending,run:()=>scope.exports.navigate({notificationId:'notice',factoryId:'f',sourceRoute:'tasks',entityId:'untrusted-client-task'},current)};
}
test('notification source uses exact server task after read and current auth, never client entity ID',async()=>{const f=fixture();await f.run();assert.equal(f.pending[0].taskId,'task-from-server');assert.equal(f.pending[0].epoch,8);assert.deepEqual(f.calls,['/notifications/notice/read','/notifications/unread-count','/auth/me']);});
test('foreign notification row cannot supply a task ID for the selected factory',async()=>{const f=fixture({notification:{factoryId:'foreign'}});await f.run();assert.equal(f.pending[0].taskId,undefined);});
test('non-task source cannot supply a task ID',async()=>{const f=fixture({notification:{entityType:'ORDER_REQUEST'}});await f.run();assert.equal(f.pending[0].taskId,undefined);});
test('notification read denial prevents any pending source navigation',async()=>{const f=fixture({readError:true});await assert.rejects(f.run(),/FORBIDDEN/);assert.equal(f.pending.length,0);assert.equal(f.calls.length,1);});
test('current permission denial prevents source navigation',async()=>{const f=fixture({allowed:false});await assert.rejects(f.run(),/Доступ к связанному разделу/);assert.equal(f.pending.length,0);});
test('late response after context cancellation cannot set source task',async()=>{const f=fixture({current:()=>false});await f.run();assert.equal(f.pending.length,0);assert.equal(f.calls.length,1);});
test('exact task source reuses linked navigation with existing dirty-form/current-context gate',()=>{assert.match(source,/if \(target === 'Tasks' && taskId\)[\s\S]*?new CustomEvent\('zavod:navigate', \{ detail: \{ screen: target, taskId \} \}\)/);assert.match(source,/if \(hasDirtyMobileForms\(\)\)[\s\S]*?taskIntent:/);});
