-- VPS-PREP-01 prerequisite snapshot.
--
-- This immutable SQL snapshot makes the historical migration chain independent
-- from backend/prisma/seed.js. It intentionally contains system Permission
-- definitions only: no role grants, factories, people or operational/demo rows.
-- The source catalog is checked against this snapshot by the targeted regression.

INSERT INTO "Permission" ("id", "code", "description") VALUES
  (gen_random_uuid(), 'admin.read', 'Read admin/config inventory'),
  (gen_random_uuid(), 'config.read', 'Read configuration inventory'),
  (gen_random_uuid(), 'admin.overview.read', 'Read admin overview'),
  (gen_random_uuid(), 'admin.users.read', 'Read admin users'),
  (gen_random_uuid(), 'admin.users.manage', 'Manage admin users and access'),
  (gen_random_uuid(), 'admin.roles.read', 'Read roles and permissions'),
  (gen_random_uuid(), 'admin.roles.manage', 'Manage role permissions'),
  (gen_random_uuid(), 'admin.factories.read', 'Read factories config'),
  (gen_random_uuid(), 'admin.factories.manage', 'Manage factories config'),
  (gen_random_uuid(), 'admin.departments.read', 'Read departments config'),
  (gen_random_uuid(), 'admin.departments.manage', 'Manage departments config'),
  (gen_random_uuid(), 'admin.lines.read', 'Read lines config'),
  (gen_random_uuid(), 'admin.lines.manage', 'Manage lines config'),
  (gen_random_uuid(), 'factory.read', 'View selected factory data'),
  (gen_random_uuid(), 'factory.manage', 'Manage factories and factory access'),
  (gen_random_uuid(), 'users.manage', 'Manage users, roles, departments and access'),
  (gen_random_uuid(), 'users.password.reset', 'Reset user passwords'),
  (gen_random_uuid(), 'lines.read', 'View lines'),
  (gen_random_uuid(), 'lines.manage', 'Manage line statuses, positions and staffing templates'),
  (gen_random_uuid(), 'assignments.manage', 'Assign and unassign employees'),
  (gen_random_uuid(), 'tasks.read', 'View tasks'),
  (gen_random_uuid(), 'tasks.create', 'Create tasks'),
  (gen_random_uuid(), 'tasks.take', 'Take tasks into work'),
  (gen_random_uuid(), 'tasks.done', 'Complete tasks'),
  (gen_random_uuid(), 'tasks.redirect', 'Redirect tasks'),
  (gen_random_uuid(), 'tasks.comment', 'Comment tasks'),
  (gen_random_uuid(), 'tasks.read-receipts.read', 'Read task receipts'),
  (gen_random_uuid(), 'tasks.escalation.manage', 'Manage task escalation'),
  (gen_random_uuid(), 'tasks.manage', 'Create and manage tasks'),
  (gen_random_uuid(), 'tasks.settings.read', 'Read task settings'),
  (gen_random_uuid(), 'tasks.settings.manage', 'Manage task settings'),
  (gen_random_uuid(), 'wash.read', 'View wash sessions'),
  (gen_random_uuid(), 'wash.manage', 'Start and complete wash sessions'),
  (gen_random_uuid(), 'wash.message.create', 'Create wash messages'),
  (gen_random_uuid(), 'wash.issue.create', 'Create wash issues'),
  (gen_random_uuid(), 'wash.issue.resolve', 'Resolve wash issues'),
  (gen_random_uuid(), 'wash.control.create', 'Create wash control items and mini tasks'),
  (gen_random_uuid(), 'wash.control.manage', 'Manage wash control items and mini tasks'),
  (gen_random_uuid(), 'wash.okk-review.read', 'Read wash OKK reviews'),
  (gen_random_uuid(), 'wash.okk-review.manage', 'Create wash OKK reviews'),
  (gen_random_uuid(), 'wash.settings.read', 'Read wash settings'),
  (gen_random_uuid(), 'wash.settings.manage', 'Manage wash settings'),
  (gen_random_uuid(), 'okk.read', 'View OKK records'),
  (gen_random_uuid(), 'okk.manage', 'Create and manage OKK records'),
  (gen_random_uuid(), 'stock.read', 'View stock defects'),
  (gen_random_uuid(), 'stock.manage', 'Create and manage stock defects'),
  (gen_random_uuid(), 'returns.read', 'View returns'),
  (gen_random_uuid(), 'returns.publication.read', 'Просмотр публикаций возвратов без права управления'),
  (gen_random_uuid(), 'returns.manage', 'Create and manage returns'),
  (gen_random_uuid(), 'orders.read', 'View orders/minimum stock'),
  (gen_random_uuid(), 'orders.take', 'Take minimum stock items into work'),
  (gen_random_uuid(), 'orders.request', 'Create replenishment order requests'),
  (gen_random_uuid(), 'orders.restock', 'Restock minimum stock items'),
  (gen_random_uuid(), 'orders.items.manage', 'Create and manage minimum stock items'),
  (gen_random_uuid(), 'orders.requests.manage', 'Close order requests'),
  (gen_random_uuid(), 'orders.archive.read', 'View orders/minimum stock archive'),
  (gen_random_uuid(), 'orders.settings.read', 'Read orders/minimum stock settings'),
  (gen_random_uuid(), 'orders.settings.manage', 'Manage orders/minimum stock settings'),
  (gen_random_uuid(), 'checklists.templates.read', 'Read checklist templates'),
  (gen_random_uuid(), 'checklists.templates.manage', 'Manage checklist templates'),
  (gen_random_uuid(), 'checklists.runs.read', 'Read checklist runs'),
  (gen_random_uuid(), 'checklists.runs.manage', 'Manage checklist runs'),
  (gen_random_uuid(), 'checklists.runs.self', 'Start and fill own checklist runs'),
  (gen_random_uuid(), 'checklists.archive.read', 'Read checklist archive'),
  (gen_random_uuid(), 'checklists.settings.read', 'Read checklist settings'),
  (gen_random_uuid(), 'checklists.settings.manage', 'Manage checklist settings'),
  (gen_random_uuid(), 'shift-log.read', 'View shift log'),
  (gen_random_uuid(), 'shift-log.create', 'Create shift log entries'),
  (gen_random_uuid(), 'shift-log.comment', 'Comment shift log entries'),
  (gen_random_uuid(), 'shift-log.manage', 'Create and manage shift log records'),
  (gen_random_uuid(), 'shift-log.important.manage', 'Manage important shift log notices'),
  (gen_random_uuid(), 'shift-log.archive.read', 'Read shift log archive'),
  (gen_random_uuid(), 'shift-log.reads.read', 'Read shift log acknowledgements'),
  (gen_random_uuid(), 'defrost.read', 'Read defrost events'),
  (gen_random_uuid(), 'defrost.manage', 'Start and complete defrost events'),
  (gen_random_uuid(), 'defrost.calendar.read', 'Read defrost calendar'),
  (gen_random_uuid(), 'defrost.settings.read', 'Read defrost settings'),
  (gen_random_uuid(), 'defrost.settings.manage', 'Manage defrost settings'),
  (gen_random_uuid(), 'chats.read', 'Read visible chats'),
  (gen_random_uuid(), 'chats.write', 'Write messages in visible chats'),
  (gen_random_uuid(), 'chats.manage', 'Create and manage scoped chats'),
  (gen_random_uuid(), 'chats.archive.read', 'Read chat archive'),
  (gen_random_uuid(), 'chats.settings.read', 'Read chat settings'),
  (gen_random_uuid(), 'chats.settings.manage', 'Manage chat settings'),
  (gen_random_uuid(), 'notifications.read', 'Read own and scoped notifications'),
  (gen_random_uuid(), 'ops.overview.read', 'Read operational overview'),
  (gen_random_uuid(), 'ops.events.read', 'Read operational event timeline'),
  (gen_random_uuid(), 'ops.audit.read', 'Read scoped operational audit'),
  (gen_random_uuid(), 'ops.audit.full', 'Read full operational audit including access-denied details'),
  (gen_random_uuid(), 'ops.statistics.read', 'Read operational module summaries'),
  (gen_random_uuid(), 'audit.read', 'View audit log'),
  (gen_random_uuid(), 'announcements.read', 'View announcements'),
  (gen_random_uuid(), 'announcements.create', 'Create announcements'),
  (gen_random_uuid(), 'announcements.manage', 'Manage announcements'),
  (gen_random_uuid(), 'announcements.archive.read', 'Read announcement archive'),
  (gen_random_uuid(), 'announcements.settings.read', 'Read announcement settings'),
  (gen_random_uuid(), 'announcements.settings.manage', 'Manage announcement settings'),
  (gen_random_uuid(), 'people.read', 'Read people directory'),
  (gen_random_uuid(), 'people.profile.read', 'Read people profiles'),
  (gen_random_uuid(), 'people.profile.manage', 'Manage people profiles'),
  (gen_random_uuid(), 'people.phone.read', 'Read visible phone numbers'),
  (gen_random_uuid(), 'people.skills.read', 'Read people skills'),
  (gen_random_uuid(), 'people.skills.manage', 'Manage people skills'),
  (gen_random_uuid(), 'people.recommendations.manage', 'Manage skill recommendations'),
  (gen_random_uuid(), 'people.notes.read', 'Read management profile notes'),
  (gen_random_uuid(), 'people.notes.manage', 'Manage management profile notes'),
  (gen_random_uuid(), 'shift.self.read', 'View own shift and employee card'),
  (gen_random_uuid(), 'shift.self.manage', 'Manage own shift attendance'),
  (gen_random_uuid(), 'shift.future.read', 'Read future shift planning'),
  (gen_random_uuid(), 'shift.future.manage', 'Manage future shift planning'),
  (gen_random_uuid(), 'shift.current.read', 'Read current shift operations'),
  (gen_random_uuid(), 'shift.current.manage', 'Manage current shift operations'),
  (gen_random_uuid(), 'shift.past.read', 'Read operational shift history'),
  (gen_random_uuid(), 'shift.return.manage', 'Approve or reject return-to-shift requests'),
  (gen_random_uuid(), 'shift.contractor-lead.manage', 'Submit contractor shift plans'),
  (gen_random_uuid(), 'shift.settings.read', 'Read shift settings'),
  (gen_random_uuid(), 'shift.settings.manage', 'Manage shift settings'),
  (gen_random_uuid(), 'company.members.read', 'Read members of the selected external company'),
  (gen_random_uuid(), 'company.members.manage', 'Manage members of the selected external company')
ON CONFLICT ("code") DO NOTHING;

