import {test,expect} from '@playwright/test';
import {isolate,json,open,shot,unknown,errors,network,records,save,installEvidenceHooks,linkedReplies,lineRow} from './helpers/frontend-series';
installEvidenceHooks();

test('Journey J23 J24 populated Ops query projections Audit labels Back and honest error recovery',async({page})=>{
  const summary=Object.fromEntries(['totalLostMinutes','downtimeCount','averageDowntimeMinutes','medianDowntimeMinutes','p90DowntimeMinutes','openDowntimeCount','urgentOpenTasks','overdueLongTasks','tasksTotal','tasksOpen','tasksCompleted','averageResponseMinutes','medianResponseMinutes','p90ResponseMinutes','maxResponseMinutes','averageExecutionMinutes','medianExecutionMinutes','p90ExecutionMinutes','maxExecutionMinutes','averageResolutionMinutes','medianResolutionMinutes','p90ResolutionMinutes'].map(k=>[k,12]));
  Object.assign(summary,{totalLostLabel:'2 ч 24 мин',preliminary:false,tenMinuteDailyEffect:{yearlyLabel:'12 ч',text:'Только подтверждённые потери'}});
  const operations={generatedAt:'2026-09-15T05:00:00Z',period:{label:'14–15 сентября 2026',days:2,capped:false,asOf:'2026-09-15T05:00:00Z'},summary,weakSpots:[],lineEvents:{stop:2,pause:3,work:5,downtimeLinkedTasks:1},quality:{okkDefects:2,stockDefects:1,stockDefectQuantity:4,returns:3},checklists:{started:5,active:1,runsCompleted:4,checksCompleted:8,checksOverdue:1,manuallyClosed:2,shiftClosed:2},wash:{active:1,completed:3,issues:1,openIssues:0,miniTasks:2,miniTasksDone:2},lines:[],downtimeReasons:[],downtimes:[],tasks:[],departments:[],repeatedProblems:[],dataQuality:{status:'Проверено',warnings:[]},limitations:['Изолированный DTO: не финансовое доказательство'],filterOptions:{lines:[lineRow],departments:[{id:'series-department',name:'Механики'}]}};
  const overview=Object.fromEntries(['activeTasksCount','overdueLongTasksCount','activeWashCount','washIssuesCount','activeDefrostCount','lowStockItemsCount','openOrderRequestsCount','activeImportantShiftLogsCount','unreadNotificationsCount','checklistAutoClosedCount','recentAccessDeniedCount'].map(k=>[k,2]));
  const audit={id:'memory-audit',module:'tasks',action:'TASK_TAKEN',actionLabel:'Заявка взята в работу',entityType:'Task',entityLabel:'Заявка',entityName:'Проверка датчика',entityId:'memory-private-reference',actorName:'Мастер смены',createdAt:'2026-09-15T05:00:00Z',detailRows:[{label:'Статус',before:'Новая',after:'В работе'},{label:'Причина',value:'Плановый осмотр'}]};
  const requests:any[]=[];let deny=false;
  await isolate(page,{theme:'gray',replies:async(r,p)=>{if(!p.startsWith('/ops/'))return linkedReplies(r,p);const params=Object.fromEntries(new URL(r.request().url()).searchParams);requests.push({p,params});
    if(p==='/ops/operations/overview'){await json(r,deny?{message:'Ошибка сервиса'}:operations,deny?503:200);return true;}
    if(p==='/ops/overview'){await json(r,overview);return true;}if(p==='/ops/audit'){await json(r,[audit]);return true;}if(p==='/ops/events'){await json(r,[{...audit,source:'audit',severity:'INFO',message:'Заявка взята в работу'}]);return true;}if(p==='/ops/module-summary'){await json(r,[{module:'tasks',count:12,scopeLabel:'За выбранный период'}]);return true;}return false;
  }});await page.setViewportSize({width:390,height:844});await page.goto('/');await open(page,'Статистика');await expect(page.locator('.ops-metric-grid .metric-card').first()).toBeVisible();await page.getByRole('button',{name:'Фильтры',exact:true}).click();
  const sheet=page.getByRole('dialog');await sheet.getByLabel('С',{exact:true}).fill('2026-09-14');await sheet.getByLabel('По',{exact:true}).fill('2026-09-15');await sheet.getByRole('combobox',{name:'Линия',exact:true}).selectOption('series-line');await sheet.getByRole('combobox',{name:'Отдел',exact:true}).selectOption('series-department');await sheet.getByRole('combobox',{name:'Смена',exact:true}).selectOption('NIGHT');await sheet.getByRole('combobox',{name:'Тип заявки',exact:true}).selectOption('LONG');await sheet.getByLabel('Поиск в событиях и аудите',{exact:true}).fill('  датчик  ');await sheet.getByLabel('Только отказы доступа',{exact:true}).check();await sheet.getByRole('button',{name:'Применить фильтры',exact:true}).click();await expect(sheet).toHaveCount(0);
  expect(requests.filter(r=>r.p==='/ops/operations/overview').at(-1).params).toMatchObject({dateFrom:'2026-09-14',dateTo:'2026-09-15',lineId:'series-line',departmentId:'series-department',shiftType:'NIGHT',taskType:'LONG'});expect(requests.filter(r=>r.p==='/ops/audit').at(-1).params).toMatchObject({dateFrom:'2026-09-14',dateTo:'2026-09-15',departmentId:'series-department',search:'датчик',accessDeniedOnly:'true'});expect(requests.filter(r=>r.p==='/ops/audit').at(-1).params).not.toHaveProperty('lineId');
  await page.getByRole('button',{name:'Аудит',exact:true}).click();await page.locator('.ops-audit-card').getByRole('button',{name:'Подробнее',exact:true}).click();await expect(page.locator('.ops-audit-detail')).toContainText('Новая → В работе');await expect(page.locator('.ops-audit-detail')).toContainText('Мастер смены');expect(await page.locator('.ops-audit-screen').innerText()).not.toContain('memory-private-reference');await shot(page,'J24-audit-human-detail',{state:'human-projected-fields-no-raw-primary-id'});await page.goBack();await expect(page.locator('.ops-audit-card')).toContainText('Проверка датчика');
  await page.getByRole('button',{name:'Потери',exact:true}).click();
  // Filter failure is not a zero-result success; existing recovery is re-entering the screen.
  await page.getByRole('button',{name:'Фильтры',exact:true}).click();deny=true;await page.getByRole('button',{name:'Применить фильтры',exact:true}).click();await expect(page.locator('.error-state')).toContainText('Ошибка сервера');await expect(page.locator('.ops-metric-grid .metric-card')).toHaveCount(0);deny=false;await open(page,'Сообщить');await open(page,'Статистика');await expect(page.locator('.ops-metric-grid .metric-card').first()).toBeVisible();await shot(page,'J23-ops-populated-recovery',{state:'nonzero-canonical-shaped-response-filter-and-recovery'});records.push({journey:'J23-J24',requests});save();expect(unknown).toEqual([]);expect(errors).toEqual([]);
});

test('Journey J12 J13 real checklist typed runner empty validation 503 retry reopen numeric zero',async({page})=>{
  const rows=[{id:'memory-number',title:'Температура датчика',rowType:'NUMBER',status:'PENDING',sortOrder:0,minValue:0,maxValue:10,unit:'°C'},{id:'memory-text',title:'Результат осмотра',rowType:'TEXT',status:'PENDING',sortOrder:1}].map(r=>({...r,requiredAnswer:true,requiresPhoto:false,requiresComment:false,isRequired:true,attachments:[]}));
  const run={id:'memory-run',userId:'series-user',status:'ACTIVE',startedAt:'2026-09-15T05:00:00Z',frequencyRule:'MANUAL',shiftDate:'2026-09-15',shiftType:'DAY',shiftLabel:'День',template:{id:'memory-template',name:'Осмотр перед запуском'},rows};let denied=true,offline=false,attempts=0;
  await isolate(page,{role:'TECH_MECHANIC',granted:['checklists.runs.self','checklists.templates.read','notifications.read'],replies:async(r,p)=>{
    if(p==='/checklists/workspace'){await json(r,{generatedAt:new Date().toISOString(),shift:{shiftDate:'2026-09-15',shiftType:'DAY',startsAt:'2026-09-15T05:00:00Z',endsAt:'2026-09-15T17:00:00Z'},activeRuns:[run],completedRuns:[],available:[],manager:null});return true;}
    if(p==='/checklists/templates/library'){await json(r,[]);return true;}
    if(p==='/directory/lines'){await json(r,[lineRow]);return true;}
    if(p==='/checklists/archive'){await json(r,{runs:[],templates:[]});return true;}
    if(p==='/checklists/archive/by-template'){await json(r,{columns:[],rows:[]});return true;}
    if(p==='/checklists/runs/memory-run'){await json(r,run);return true;}
    if(p==='/checklists/runs/memory-run/rows/memory-number/complete'){attempts++;const body=r.request().postDataJSON();expect(body.answerNumber).toBe('0');if(offline){await r.abort('connectionrefused');return true;}if(!denied)Object.assign(rows[0],{status:'OK',answerNumber:0,answerText:'0'});await json(r,denied?{message:'Не удалось сохранить'}:{...rows[0]},denied?503:200);return true;}
    return false;
  }});await page.setViewportSize({width:390,height:844});await page.goto('/');await open(page,'Чек-листы');await page.locator('[data-checklist-run-id=memory-run]').getByRole('button',{name:'Продолжить',exact:true}).click();
  await page.getByRole('button',{name:'Дальше',exact:true}).click();await expect(page.locator('.error-state').last()).toContainText('Заполните значение');expect(attempts).toBe(0);
  await page.getByLabel('Значение',{exact:false}).fill('0');await page.getByRole('button',{name:'Дальше',exact:true}).click();await expect(page.locator('.error-state').last()).toContainText('Ошибка сервера');await expect(page.getByLabel('Значение',{exact:false})).toHaveValue('0');expect(attempts).toBe(1);
  offline=true;await page.getByRole('button',{name:'Дальше',exact:true}).click();await expect(page.locator('.guided-save-state')).toHaveText('Нет связи. Ответ не сохранён.');expect(attempts).toBe(2);
  offline=false;denied=false;await page.locator('.guided-progress').getByRole('button',{name:'Повторить',exact:true}).click();await expect(page.locator('.guided-save-state')).toHaveText('Сохранено');await page.getByRole('button',{name:'Дальше',exact:true}).click();await expect(page.locator('.guided-current-row')).toContainText('Результат осмотра');expect(attempts).toBe(3);
  await page.getByRole('button',{name:'Проверить и завершить',exact:true}).click();await expect(page.locator('.error-state').last()).toContainText('Заполните текстовый ответ');
  await page.getByRole('button',{name:'Вернуться к чек-листам',exact:true}).click();await page.locator('[data-checklist-run-id=memory-run]').getByRole('button',{name:'Продолжить',exact:true}).click();await page.locator('.guided-navigation').getByRole('button',{name:'Назад',exact:true}).click();await expect(page.getByLabel('Значение',{exact:false})).toHaveValue('0');
  await shot(page,'J13-numeric-zero-retry',{state:'real-runner-reopen-numeric-zero'});expect(unknown).toEqual([]);expect(errors).toEqual([]);
});

test('Journey J22 all archive categories list detail denial retry export keep canonical query and Back',async({page})=>{
  test.setTimeout(90000);
  const sections=[['tasks','TASK'],['checklists','CHECKLIST_RUN'],['okk','OKK_RECORD'],['returns','RETURN_RECORD'],['stock','STOCK_DEFECT'],['orders','MINIMUM_STOCK_MOVEMENT'],['wash','WASH_SESSION'],['defrost','DEFROST_EVENT'],['shiftLog','SHIFT_LOG'],['announcements','ANNOUNCEMENT'],['attachments','CHAT_MESSAGE']];
  let deny=true;const queryRecords:any[]=[];
  const titles:Record<string,string>={tasks:'Заявка на осмотр',checklists:'Результат проверки',okk:'Контроль качества',returns:'Возврат партии',stock:'Некондиция упаковки',orders:'Пополнение остатка',wash:'Мойка оборудования',defrost:'Оттайка камеры',shiftLog:'Передача смены',announcements:'Уведомление отдела'};
  const row=(section:string,sourceType:string)=>({id:'memory-'+section,sourceId:'memory-'+section,sourceType,section,title:titles[section]??'Осмотр оборудования',date:'2026-09-15T05:00:00Z',status:'DONE',departmentName:'Механики',lineName:'Линия фасовки',authorName:'Мастер смены',summary:'Проверка оборудования завершена',hasAttachments:false});
  const file={id:'memory-archive-file',filename:'Инструкция.txt',kind:'FILE',mimeType:'text/plain',size:12,createdAt:'2026-09-15T05:00:00Z',author:'Мастер смены',sourceType:'CHAT_MESSAGE',sourceId:'memory-message',sourceTitle:'Обсуждение оборудования',downloadAllowed:true};
  await isolate(page,{replies:async(r,p)=>{
    const q=new URL(r.request().url()).searchParams;
    if(p==='/archive/options'){await json(r,{sections:sections.map(([key])=>({key,label:key,description:''})),lines:[lineRow],departments:[{id:'series-department',name:'Механики'}],checklistTemplates:[]});return true;}
    if(p==='/archive/downtime/options'){await json(r,{lines:[lineRow],departments:[],assignees:[],reasons:[]});return true;}
    if(p==='/archive/items'){queryRecords.push(Object.fromEntries(q));const section=q.get('section')!;const type=sections.find(s=>s[0]===section)![1];await json(r,{items:[row(section,type)],page:Number(q.get('page')),pageSize:Number(q.get('pageSize')),total:1,hasMore:false});return true;}
    if(p==='/archive/attachments'){await json(r,{items:[file],page:1,pageSize:24,total:1,hasMore:false});return true;}
    if(p.startsWith('/archive/detail/')){const[section,type]=p.split('/').slice(3);await json(r,deny?{message:'Нет доступа к записи.'}:{...row(section,type),sourceRoute:null,sections:[{title:'Результат',fields:[{label:'Итог',value:'Проверка оборудования завершена'}]}],attachments:[]},deny?403:200);return true;}
    if(p==='/attachments/memory-archive-file/file'){await r.fulfill({contentType:'text/plain',body:'Инструкция'});return true;}
    return linkedReplies(r,p);
  }});await page.setViewportSize({width:390,height:844});await page.goto('/');await open(page,'Архив');
  for(const[section]of sections){await page.locator(`[data-archive-category="${section}"]`).click();await page.getByLabel('Поиск в архиве',{exact:true}).fill('оборудование');await page.getByRole('button',{name:'Найти',exact:true}).click();
    await page.locator('.archive-record-open').click();if(section!=='attachments'){await expect(page.locator('.error-state')).toContainText('Нет доступа');await expect(page.locator('.archive-detail-sheet')).toHaveCount(0);deny=false;await page.locator('.archive-record-open').click();await expect(page.locator('.archive-detail-sheet')).toContainText('Проверка оборудования завершена');}else await expect(page.locator('.archive-detail-sheet')).toContainText('Инструкция.txt');
    await page.goBack();await expect(page.getByLabel('Поиск в архиве',{exact:true})).toHaveValue('оборудование');
    if(section==='tasks'||section==='orders'){await page.getByRole('button',{name:'Экспорт архива',exact:true}).click();const download=page.waitForEvent('download');await page.getByRole('button',{name:/CSV \(для интеграций\)/}).click();await download;await expect(page.locator('.archive-save-notice')).toContainText('1 записей');expect(queryRecords.at(-1)).toMatchObject({section,search:'оборудование',page:'1',pageSize:'100'});}
    records.push({journey:'J22',section,listDetailBack:true,query:queryRecords.at(-1),scope:'browser-shaped-memory-only'});save();deny=true;await page.getByRole('button',{name:'Назад к разделам архива',exact:true}).click();
  }
  await shot(page,'J22-category-return',{state:'all-11-current-categories'});expect(unknown).toEqual([]);expect(errors).toEqual([]);
});
